// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module computerWindow (
        ap_clk,
        ap_rst,
        window_val_0_2_rea,
        window_val_0_3_rea,
        window_val_0_4_rea,
        window_val_1_1_rea,
        window_val_1_5_rea,
        window_val_2_0_rea,
        window_val_2_6_rea,
        window_val_3_0_rea,
        window_val_3_3_rea,
        window_val_3_6_rea,
        window_val_4_0_rea,
        window_val_4_6_rea,
        window_val_5_1_rea,
        window_val_5_5_rea,
        window_val_6_2_rea,
        window_val_6_3_rea,
        window_val_6_4_rea,
        threshold_data,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] window_val_0_2_rea;
input  [31:0] window_val_0_3_rea;
input  [31:0] window_val_0_4_rea;
input  [31:0] window_val_1_1_rea;
input  [31:0] window_val_1_5_rea;
input  [31:0] window_val_2_0_rea;
input  [31:0] window_val_2_6_rea;
input  [31:0] window_val_3_0_rea;
input  [31:0] window_val_3_3_rea;
input  [31:0] window_val_3_6_rea;
input  [31:0] window_val_4_0_rea;
input  [31:0] window_val_4_6_rea;
input  [23:0] window_val_5_1_rea;
input  [23:0] window_val_5_5_rea;
input  [23:0] window_val_6_2_rea;
input  [23:0] window_val_6_3_rea;
input  [23:0] window_val_6_4_rea;
input  [8:0] threshold_data;
output  [0:0] ap_return;
input   ap_ce;

reg[0:0] ap_return;

reg   [8:0] threshold_data_read_reg_3527;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [11:0] tmp_5_reg_3532;
reg   [11:0] tmp_10_reg_3537;
reg   [11:0] tmp_16_reg_3542;
reg   [11:0] tmp_24_reg_3547;
reg   [11:0] tmp_30_reg_3552;
reg   [11:0] tmp_47_reg_3557;
reg   [11:0] tmp_51_reg_3562;
reg   [11:0] tmp_56_reg_3567;
reg   [11:0] tmp_61_reg_3572;
reg   [11:0] tmp_65_reg_3577;
reg   [11:0] tmp_69_reg_3582;
reg   [11:0] tmp_73_reg_3587;
reg   [11:0] tmp_77_reg_3592;
reg   [11:0] tmp_81_reg_3597;
reg   [11:0] tmp_85_reg_3602;
reg   [11:0] tmp_89_reg_3607;
reg   [11:0] tmp_93_reg_3612;
wire   [0:0] tmp_18_fu_1580_p2;
reg   [0:0] tmp_18_reg_3617;
reg   [0:0] tmp_18_reg_3617_pp0_iter2_reg;
reg   [0:0] tmp_18_reg_3617_pp0_iter3_reg;
reg   [0:0] tmp_18_reg_3617_pp0_iter4_reg;
reg   [0:0] tmp_18_reg_3617_pp0_iter5_reg;
reg   [0:0] tmp_18_reg_3617_pp0_iter6_reg;
wire   [0:0] tmp_32_fu_1622_p2;
reg   [0:0] tmp_32_reg_3623;
wire   [0:0] tmp_34_fu_1654_p2;
reg   [0:0] tmp_34_reg_3629;
wire   [0:0] tmp_36_fu_1690_p2;
reg   [0:0] tmp_36_reg_3634;
wire   [0:0] tmp_38_fu_1726_p2;
reg   [0:0] tmp_38_reg_3639;
wire   [0:0] tmp_44_fu_1758_p2;
reg   [0:0] tmp_44_reg_3644;
wire   [0:0] tmp_111_1_fu_1797_p2;
reg   [0:0] tmp_111_1_reg_3650;
wire   [0:0] tmp_111_2_fu_1836_p2;
reg   [0:0] tmp_111_2_reg_3657;
wire   [0:0] tmp_111_3_fu_1875_p2;
reg   [0:0] tmp_111_3_reg_3664;
wire   [0:0] tmp_111_4_fu_1907_p2;
reg   [0:0] tmp_111_4_reg_3671;
reg   [0:0] tmp_111_4_reg_3671_pp0_iter2_reg;
wire   [0:0] tmp_111_5_fu_1946_p2;
reg   [0:0] tmp_111_5_reg_3678;
reg   [0:0] tmp_111_5_reg_3678_pp0_iter2_reg;
wire   [0:0] tmp_111_6_fu_1985_p2;
reg   [0:0] tmp_111_6_reg_3685;
reg   [0:0] tmp_111_6_reg_3685_pp0_iter2_reg;
wire   [0:0] tmp_111_7_fu_2024_p2;
reg   [0:0] tmp_111_7_reg_3692;
reg   [0:0] tmp_111_7_reg_3692_pp0_iter2_reg;
reg   [0:0] tmp_111_7_reg_3692_pp0_iter3_reg;
wire   [0:0] tmp_111_8_fu_2056_p2;
reg   [0:0] tmp_111_8_reg_3699;
reg   [0:0] tmp_111_8_reg_3699_pp0_iter2_reg;
reg   [0:0] tmp_111_8_reg_3699_pp0_iter3_reg;
wire   [0:0] tmp_111_9_fu_2095_p2;
reg   [0:0] tmp_111_9_reg_3706;
reg   [0:0] tmp_111_9_reg_3706_pp0_iter2_reg;
reg   [0:0] tmp_111_9_reg_3706_pp0_iter3_reg;
wire   [0:0] tmp_111_s_fu_2134_p2;
reg   [0:0] tmp_111_s_reg_3713;
reg   [0:0] tmp_111_s_reg_3713_pp0_iter2_reg;
reg   [0:0] tmp_111_s_reg_3713_pp0_iter3_reg;
reg   [0:0] tmp_111_s_reg_3713_pp0_iter4_reg;
wire   [0:0] tmp_111_10_fu_2173_p2;
reg   [0:0] tmp_111_10_reg_3720;
reg   [0:0] tmp_111_10_reg_3720_pp0_iter2_reg;
reg   [0:0] tmp_111_10_reg_3720_pp0_iter3_reg;
reg   [0:0] tmp_111_10_reg_3720_pp0_iter4_reg;
wire   [0:0] tmp_111_11_fu_2205_p2;
reg   [0:0] tmp_111_11_reg_3727;
reg   [0:0] tmp_111_11_reg_3727_pp0_iter2_reg;
reg   [0:0] tmp_111_11_reg_3727_pp0_iter3_reg;
reg   [0:0] tmp_111_11_reg_3727_pp0_iter4_reg;
wire   [0:0] tmp_111_12_fu_2244_p2;
reg   [0:0] tmp_111_12_reg_3734;
reg   [0:0] tmp_111_12_reg_3734_pp0_iter2_reg;
reg   [0:0] tmp_111_12_reg_3734_pp0_iter3_reg;
reg   [0:0] tmp_111_12_reg_3734_pp0_iter4_reg;
reg   [0:0] tmp_111_12_reg_3734_pp0_iter5_reg;
wire   [0:0] tmp_111_13_fu_2283_p2;
reg   [0:0] tmp_111_13_reg_3741;
reg   [0:0] tmp_111_13_reg_3741_pp0_iter2_reg;
reg   [0:0] tmp_111_13_reg_3741_pp0_iter3_reg;
reg   [0:0] tmp_111_13_reg_3741_pp0_iter4_reg;
reg   [0:0] tmp_111_13_reg_3741_pp0_iter5_reg;
wire   [0:0] tmp_111_14_fu_2322_p2;
reg   [0:0] tmp_111_14_reg_3748;
reg   [0:0] tmp_111_14_reg_3748_pp0_iter2_reg;
reg   [0:0] tmp_111_14_reg_3748_pp0_iter3_reg;
reg   [0:0] tmp_111_14_reg_3748_pp0_iter4_reg;
reg   [0:0] tmp_111_14_reg_3748_pp0_iter5_reg;
wire   [0:0] icmp_fu_2403_p2;
reg   [0:0] icmp_reg_3754;
reg   [0:0] icmp_reg_3754_pp0_iter3_reg;
reg   [0:0] icmp_reg_3754_pp0_iter4_reg;
reg   [0:0] icmp_reg_3754_pp0_iter5_reg;
reg   [0:0] icmp_reg_3754_pp0_iter6_reg;
wire   [2:0] maxnum_2_4_fu_2581_p3;
reg   [2:0] maxnum_2_4_reg_3759;
wire   [2:0] num_1_4_fu_2596_p3;
reg   [2:0] num_1_4_reg_3766;
wire   [2:0] maxnum_2_7_fu_2738_p3;
reg   [2:0] maxnum_2_7_reg_3773;
wire   [3:0] num_1_7_fu_2753_p3;
reg   [3:0] num_1_7_reg_3778;
wire   [3:0] maxnum_2_s_fu_2897_p3;
reg   [3:0] maxnum_2_s_reg_3785;
wire   [3:0] num_1_s_fu_2912_p3;
reg   [3:0] num_1_s_reg_3792;
wire   [3:0] maxnum_2_12_fu_3050_p3;
reg   [3:0] maxnum_2_12_reg_3799;
wire   [3:0] num_1_12_fu_3065_p3;
reg   [3:0] num_1_12_reg_3806;
wire   [0:0] tmp_59_fu_3195_p2;
reg   [0:0] tmp_59_reg_3813;
wire    ap_block_pp0_stage0;
wire   [7:0] R_fu_208_p1;
wire   [7:0] G_fu_212_p4;
wire   [7:0] tmp_fu_230_p4;
wire   [14:0] p_shl6_fu_240_p3;
wire   [10:0] p_shl7_fu_252_p3;
wire   [15:0] p_shl6_cast_fu_248_p1;
wire   [15:0] p_shl7_cast_fu_260_p1;
wire  signed [15:0] tmp_6_fu_264_p2;
wire  signed [18:0] grp_fu_3230_p3;
wire  signed [19:0] grp_fu_3221_p3;
wire   [7:0] R_1_fu_286_p1;
wire   [7:0] G_1_fu_290_p4;
wire   [7:0] tmp_3_fu_308_p4;
wire   [14:0] p_shl4_fu_318_p3;
wire   [10:0] p_shl5_fu_330_p3;
wire   [15:0] p_shl4_cast_fu_326_p1;
wire   [15:0] p_shl5_cast_fu_338_p1;
wire  signed [15:0] tmp_1_fu_342_p2;
wire  signed [18:0] grp_fu_3248_p3;
wire  signed [19:0] grp_fu_3239_p3;
wire   [7:0] R_2_fu_364_p1;
wire   [7:0] G_2_fu_368_p4;
wire   [7:0] tmp_13_fu_386_p4;
wire   [14:0] p_shl_fu_396_p3;
wire   [10:0] p_shl3_fu_408_p3;
wire   [15:0] p_shl_cast_fu_404_p1;
wire   [15:0] p_shl3_cast_fu_416_p1;
wire  signed [15:0] tmp_14_fu_420_p2;
wire  signed [18:0] grp_fu_3266_p3;
wire  signed [19:0] grp_fu_3257_p3;
wire   [7:0] R_3_fu_442_p1;
wire   [7:0] G_3_fu_446_p4;
wire   [7:0] tmp_21_fu_464_p4;
wire   [14:0] p_shl1_fu_474_p3;
wire   [10:0] p_shl2_fu_486_p3;
wire   [15:0] p_shl1_cast_fu_482_p1;
wire   [15:0] p_shl2_cast_fu_494_p1;
wire  signed [15:0] tmp_22_fu_498_p2;
wire  signed [18:0] grp_fu_3284_p3;
wire  signed [19:0] grp_fu_3275_p3;
wire   [7:0] R_4_fu_520_p1;
wire   [7:0] G_4_fu_524_p4;
wire   [7:0] tmp_27_fu_542_p4;
wire   [14:0] p_shl8_fu_552_p3;
wire   [10:0] p_shl9_fu_564_p3;
wire   [15:0] p_shl8_cast_fu_560_p1;
wire   [15:0] p_shl9_cast_fu_572_p1;
wire  signed [15:0] tmp_28_fu_576_p2;
wire  signed [18:0] grp_fu_3302_p3;
wire  signed [19:0] grp_fu_3293_p3;
wire   [7:0] tmp_45_fu_598_p1;
wire   [7:0] G_5_1_fu_602_p4;
wire   [7:0] tmp_46_fu_620_p4;
wire   [14:0] p_shl12_1_fu_630_p3;
wire   [10:0] p_shl13_1_fu_642_p3;
wire   [15:0] p_shl12_1_cast_fu_638_p1;
wire   [15:0] p_shl13_1_cast_fu_650_p1;
wire  signed [15:0] tmp_105_1_fu_654_p2;
wire  signed [17:0] grp_fu_3311_p3;
wire  signed [19:0] grp_fu_3320_p3;
wire   [7:0] tmp_49_fu_676_p1;
wire   [7:0] G_5_2_fu_680_p4;
wire   [7:0] tmp_50_fu_698_p4;
wire   [14:0] p_shl12_2_fu_708_p3;
wire   [10:0] p_shl13_2_fu_720_p3;
wire   [15:0] p_shl12_2_cast_fu_716_p1;
wire   [15:0] p_shl13_2_cast_fu_728_p1;
wire  signed [15:0] tmp_105_2_fu_732_p2;
wire  signed [18:0] grp_fu_3338_p3;
wire  signed [19:0] grp_fu_3329_p3;
wire   [7:0] tmp_53_fu_754_p1;
wire   [7:0] G_5_3_fu_758_p4;
wire   [7:0] tmp_54_fu_776_p4;
wire   [14:0] p_shl12_3_fu_786_p3;
wire   [10:0] p_shl13_3_fu_798_p3;
wire   [15:0] p_shl12_3_cast_fu_794_p1;
wire   [15:0] p_shl13_3_cast_fu_806_p1;
wire  signed [15:0] tmp_105_3_fu_810_p2;
wire  signed [18:0] grp_fu_3356_p3;
wire  signed [19:0] grp_fu_3347_p3;
wire   [7:0] tmp_58_fu_832_p1;
wire   [7:0] G_5_5_fu_836_p4;
wire   [7:0] tmp_60_fu_854_p4;
wire   [14:0] p_shl12_5_fu_864_p3;
wire   [10:0] p_shl13_5_fu_876_p3;
wire   [15:0] p_shl12_5_cast_fu_872_p1;
wire   [15:0] p_shl13_5_cast_fu_884_p1;
wire  signed [15:0] tmp_105_5_fu_888_p2;
wire  signed [18:0] grp_fu_3374_p3;
wire  signed [19:0] grp_fu_3365_p3;
wire   [7:0] tmp_63_fu_910_p1;
wire   [7:0] G_5_6_fu_914_p4;
wire   [7:0] tmp_64_fu_932_p4;
wire   [14:0] p_shl12_6_fu_942_p3;
wire   [10:0] p_shl13_6_fu_954_p3;
wire   [15:0] p_shl12_6_cast_fu_950_p1;
wire   [15:0] p_shl13_6_cast_fu_962_p1;
wire  signed [15:0] tmp_105_6_fu_966_p2;
wire  signed [18:0] grp_fu_3392_p3;
wire  signed [19:0] grp_fu_3383_p3;
wire   [7:0] tmp_67_fu_988_p1;
wire   [7:0] G_5_7_fu_992_p4;
wire   [7:0] tmp_68_fu_1010_p4;
wire   [14:0] p_shl12_7_fu_1020_p3;
wire   [10:0] p_shl13_7_fu_1032_p3;
wire   [15:0] p_shl12_7_cast_fu_1028_p1;
wire   [15:0] p_shl13_7_cast_fu_1040_p1;
wire  signed [15:0] tmp_105_7_fu_1044_p2;
wire  signed [18:0] grp_fu_3410_p3;
wire  signed [19:0] grp_fu_3401_p3;
wire   [7:0] tmp_71_fu_1066_p1;
wire   [7:0] G_5_9_fu_1070_p4;
wire   [7:0] tmp_72_fu_1088_p4;
wire   [14:0] p_shl12_9_fu_1098_p3;
wire   [10:0] p_shl13_9_fu_1110_p3;
wire   [15:0] p_shl12_9_cast_fu_1106_p1;
wire   [15:0] p_shl13_9_cast_fu_1118_p1;
wire  signed [15:0] tmp_105_9_fu_1122_p2;
wire  signed [18:0] grp_fu_3428_p3;
wire  signed [19:0] grp_fu_3419_p3;
wire   [7:0] tmp_75_fu_1144_p1;
wire   [7:0] G_5_s_fu_1148_p4;
wire   [7:0] tmp_76_fu_1166_p4;
wire   [14:0] p_shl12_s_fu_1176_p3;
wire   [10:0] p_shl13_s_fu_1188_p3;
wire   [15:0] p_shl12_cast_fu_1184_p1;
wire   [15:0] p_shl13_cast_fu_1196_p1;
wire  signed [15:0] tmp_105_s_fu_1200_p2;
wire  signed [18:0] grp_fu_3446_p3;
wire  signed [19:0] grp_fu_3437_p3;
wire   [7:0] tmp_79_fu_1222_p1;
wire   [7:0] G_5_4_fu_1226_p4;
wire   [7:0] tmp_80_fu_1244_p4;
wire   [14:0] p_shl12_4_fu_1254_p3;
wire   [10:0] p_shl13_4_fu_1266_p3;
wire   [15:0] p_shl12_4_cast_fu_1262_p1;
wire   [15:0] p_shl13_4_cast_fu_1274_p1;
wire  signed [15:0] tmp_105_4_fu_1278_p2;
wire  signed [18:0] grp_fu_3464_p3;
wire  signed [19:0] grp_fu_3455_p3;
wire   [7:0] tmp_83_fu_1300_p1;
wire   [7:0] G_5_8_fu_1304_p4;
wire   [7:0] tmp_84_fu_1322_p4;
wire   [14:0] p_shl12_8_fu_1332_p3;
wire   [10:0] p_shl13_8_fu_1344_p3;
wire   [15:0] p_shl12_8_cast_fu_1340_p1;
wire   [15:0] p_shl13_8_cast_fu_1352_p1;
wire  signed [15:0] tmp_105_8_fu_1356_p2;
wire  signed [18:0] grp_fu_3482_p3;
wire  signed [19:0] grp_fu_3473_p3;
wire   [7:0] tmp_87_fu_1378_p1;
wire   [7:0] G_5_10_fu_1382_p4;
wire   [7:0] tmp_88_fu_1400_p4;
wire   [14:0] p_shl12_10_fu_1410_p3;
wire   [10:0] p_shl13_10_fu_1422_p3;
wire   [15:0] p_shl12_10_cast_fu_1418_p1;
wire   [15:0] p_shl13_10_cast_fu_1430_p1;
wire  signed [15:0] tmp_105_10_fu_1434_p2;
wire  signed [18:0] grp_fu_3500_p3;
wire  signed [19:0] grp_fu_3491_p3;
wire   [7:0] tmp_91_fu_1456_p1;
wire   [7:0] G_5_11_fu_1460_p4;
wire   [7:0] tmp_92_fu_1478_p4;
wire   [14:0] p_shl12_11_fu_1488_p3;
wire   [10:0] p_shl13_11_fu_1500_p3;
wire   [15:0] p_shl12_11_cast_fu_1496_p1;
wire   [15:0] p_shl13_11_cast_fu_1508_p1;
wire  signed [15:0] tmp_105_11_fu_1512_p2;
wire  signed [18:0] grp_fu_3518_p3;
wire  signed [19:0] grp_fu_3509_p3;
wire  signed [15:0] p2_fu_1537_p1;
wire  signed [15:0] p3_fu_1540_p1;
wire   [16:0] tmp_32_cast_fu_1543_p1;
wire   [16:0] tmp_33_cast_fu_1547_p1;
wire   [16:0] tmp_17_fu_1551_p2;
wire   [0:0] abscond_fu_1563_p2;
wire   [16:0] neg_fu_1557_p2;
wire   [16:0] abs_fu_1569_p3;
wire  signed [16:0] threshold_data_cast1_fu_1577_p1;
wire  signed [15:0] p1_fu_1534_p1;
wire   [16:0] tmp_58_cast_fu_1592_p1;
wire   [16:0] tmp_31_fu_1596_p2;
wire   [0:0] abscond1_fu_1608_p2;
wire   [16:0] neg1_fu_1602_p2;
wire   [16:0] abs1_fu_1614_p3;
wire   [16:0] tmp_33_fu_1628_p2;
wire   [0:0] abscond2_fu_1640_p2;
wire   [16:0] neg2_fu_1634_p2;
wire   [16:0] abs2_fu_1646_p3;
wire  signed [15:0] p4_fu_1586_p1;
wire   [16:0] tmp_63_cast_fu_1660_p1;
wire   [16:0] tmp_35_fu_1664_p2;
wire   [0:0] abscond3_fu_1676_p2;
wire   [16:0] neg3_fu_1670_p2;
wire   [16:0] abs3_fu_1682_p3;
wire  signed [15:0] p5_fu_1589_p1;
wire   [16:0] tmp_66_cast_fu_1696_p1;
wire   [16:0] tmp_37_fu_1700_p2;
wire   [0:0] abscond4_fu_1712_p2;
wire   [16:0] neg4_fu_1706_p2;
wire   [16:0] abs4_fu_1718_p3;
wire   [16:0] tmp_43_fu_1732_p2;
wire   [0:0] abscond5_fu_1744_p2;
wire   [16:0] neg5_fu_1738_p2;
wire   [16:0] abs5_fu_1750_p3;
wire  signed [15:0] tmp_48_fu_1764_p1;
wire   [16:0] tmp_109_1_cast_fu_1767_p1;
wire   [16:0] tmp_110_1_fu_1771_p2;
wire   [0:0] abscond5_1_fu_1783_p2;
wire   [16:0] neg5_1_fu_1777_p2;
wire   [16:0] abs5_1_fu_1789_p3;
wire  signed [15:0] tmp_52_fu_1803_p1;
wire   [16:0] tmp_109_2_cast_fu_1806_p1;
wire   [16:0] tmp_110_2_fu_1810_p2;
wire   [0:0] abscond5_2_fu_1822_p2;
wire   [16:0] neg5_2_fu_1816_p2;
wire   [16:0] abs5_2_fu_1828_p3;
wire  signed [15:0] tmp_57_fu_1842_p1;
wire   [16:0] tmp_109_3_cast_fu_1845_p1;
wire   [16:0] tmp_110_3_fu_1849_p2;
wire   [0:0] abscond5_3_fu_1861_p2;
wire   [16:0] neg5_3_fu_1855_p2;
wire   [16:0] abs5_3_fu_1867_p3;
wire   [16:0] tmp_110_4_fu_1881_p2;
wire   [0:0] abscond5_4_fu_1893_p2;
wire   [16:0] neg5_4_fu_1887_p2;
wire   [16:0] abs5_4_fu_1899_p3;
wire  signed [15:0] tmp_62_fu_1913_p1;
wire   [16:0] tmp_109_5_cast_fu_1916_p1;
wire   [16:0] tmp_110_5_fu_1920_p2;
wire   [0:0] abscond5_5_fu_1932_p2;
wire   [16:0] neg5_5_fu_1926_p2;
wire   [16:0] abs5_5_fu_1938_p3;
wire  signed [15:0] tmp_66_fu_1952_p1;
wire   [16:0] tmp_109_6_cast_fu_1955_p1;
wire   [16:0] tmp_110_6_fu_1959_p2;
wire   [0:0] abscond5_6_fu_1971_p2;
wire   [16:0] neg5_6_fu_1965_p2;
wire   [16:0] abs5_6_fu_1977_p3;
wire  signed [15:0] tmp_70_fu_1991_p1;
wire   [16:0] tmp_109_7_cast_fu_1994_p1;
wire   [16:0] tmp_110_7_fu_1998_p2;
wire   [0:0] abscond5_7_fu_2010_p2;
wire   [16:0] neg5_7_fu_2004_p2;
wire   [16:0] abs5_7_fu_2016_p3;
wire   [16:0] tmp_110_8_fu_2030_p2;
wire   [0:0] abscond5_8_fu_2042_p2;
wire   [16:0] neg5_8_fu_2036_p2;
wire   [16:0] abs5_8_fu_2048_p3;
wire  signed [15:0] tmp_74_fu_2062_p1;
wire   [16:0] tmp_109_9_cast_fu_2065_p1;
wire   [16:0] tmp_110_9_fu_2069_p2;
wire   [0:0] abscond5_9_fu_2081_p2;
wire   [16:0] neg5_9_fu_2075_p2;
wire   [16:0] abs5_9_fu_2087_p3;
wire  signed [15:0] tmp_78_fu_2101_p1;
wire   [16:0] tmp_109_cast_fu_2104_p1;
wire   [16:0] tmp_110_s_fu_2108_p2;
wire   [0:0] abscond5_s_fu_2120_p2;
wire   [16:0] neg5_s_fu_2114_p2;
wire   [16:0] abs5_s_fu_2126_p3;
wire  signed [15:0] tmp_82_fu_2140_p1;
wire   [16:0] tmp_109_4_cast_fu_2143_p1;
wire   [16:0] tmp_110_10_fu_2147_p2;
wire   [0:0] abscond5_10_fu_2159_p2;
wire   [16:0] neg5_10_fu_2153_p2;
wire   [16:0] abs5_10_fu_2165_p3;
wire   [16:0] tmp_110_11_fu_2179_p2;
wire   [0:0] abscond5_11_fu_2191_p2;
wire   [16:0] neg5_11_fu_2185_p2;
wire   [16:0] abs5_11_fu_2197_p3;
wire  signed [15:0] tmp_86_fu_2211_p1;
wire   [16:0] tmp_109_8_cast_fu_2214_p1;
wire   [16:0] tmp_110_12_fu_2218_p2;
wire   [0:0] abscond5_12_fu_2230_p2;
wire   [16:0] neg5_12_fu_2224_p2;
wire   [16:0] abs5_12_fu_2236_p3;
wire  signed [15:0] tmp_90_fu_2250_p1;
wire   [16:0] tmp_109_10_cast_fu_2253_p1;
wire   [16:0] tmp_110_13_fu_2257_p2;
wire   [0:0] abscond5_13_fu_2269_p2;
wire   [16:0] neg5_13_fu_2263_p2;
wire   [16:0] abs5_13_fu_2275_p3;
wire  signed [15:0] tmp_94_fu_2289_p1;
wire   [16:0] tmp_109_11_cast_fu_2292_p1;
wire   [16:0] tmp_110_14_fu_2296_p2;
wire   [0:0] abscond5_14_fu_2308_p2;
wire   [16:0] neg5_14_fu_2302_p2;
wire   [16:0] abs5_14_fu_2314_p3;
wire   [0:0] not_tmp_s_fu_2328_p2;
wire   [1:0] p_cast_fu_2333_p1;
wire   [1:0] k_fu_2337_p3;
wire   [1:0] k_1_fu_2344_p3;
wire   [1:0] k_2_fu_2351_p2;
wire   [1:0] k_1_s_fu_2357_p3;
wire   [2:0] k_1_cast_fu_2364_p1;
wire   [0:0] tmp_39_fu_2374_p3;
wire   [2:0] k_3_fu_2368_p2;
wire   [1:0] tmp_40_fu_2382_p1;
wire   [1:0] tmp_41_fu_2386_p4;
wire   [1:0] tmp_42_fu_2396_p3;
wire   [0:0] not_tmp_111_1_fu_2416_p2;
wire   [0:0] maxnum_2_1_fu_2421_p2;
wire   [1:0] num_2_1_fu_2409_p3;
wire   [1:0] num_1_1_fu_2430_p3;
wire   [1:0] maxnum_2_1_cast_fu_2426_p1;
wire   [0:0] tmp_112_2_fu_2443_p2;
wire   [0:0] sel_tmp5_fu_2457_p2;
wire   [0:0] sel_tmp6_fu_2462_p2;
wire   [1:0] maxnum_3_2_fu_2449_p3;
wire   [1:0] num_2_2_fu_2437_p2;
wire   [1:0] sel_tmp8_fu_2475_p3;
wire   [1:0] num_1_2_fu_2482_p3;
wire   [2:0] num_1_2_cast_fu_2490_p1;
wire   [1:0] maxnum_2_2_fu_2467_p3;
wire   [0:0] tmp_112_3_fu_2500_p2;
wire   [0:0] sel_tmp_fu_2514_p2;
wire   [0:0] sel_tmp1_fu_2519_p2;
wire   [1:0] maxnum_3_3_fu_2506_p3;
wire   [1:0] maxnum_2_3_fu_2524_p3;
wire   [2:0] num_2_3_fu_2494_p2;
wire   [2:0] sel_tmp2_fu_2536_p3;
wire   [2:0] num_1_3_fu_2543_p3;
wire   [2:0] maxnum_2_3_cast1_cas_fu_2532_p1;
wire   [0:0] tmp_112_4_fu_2557_p2;
wire   [0:0] sel_tmp3_fu_2571_p2;
wire   [0:0] sel_tmp4_fu_2576_p2;
wire   [2:0] maxnum_3_4_fu_2563_p3;
wire   [2:0] num_2_4_fu_2551_p2;
wire   [2:0] sel_tmp7_fu_2589_p3;
wire   [0:0] tmp_112_5_fu_2609_p2;
wire   [0:0] sel_tmp9_fu_2619_p2;
wire   [0:0] sel_tmp10_fu_2624_p2;
wire   [2:0] maxnum_3_5_fu_2613_p3;
wire   [2:0] num_2_5_fu_2604_p2;
wire   [2:0] sel_tmp11_fu_2636_p3;
wire   [2:0] num_1_5_fu_2643_p3;
wire   [2:0] maxnum_2_5_fu_2629_p3;
wire   [0:0] tmp_112_6_fu_2657_p2;
wire   [0:0] sel_tmp12_fu_2671_p2;
wire   [0:0] sel_tmp13_fu_2676_p2;
wire   [2:0] maxnum_3_6_fu_2663_p3;
wire   [2:0] num_2_6_fu_2651_p2;
wire   [2:0] sel_tmp14_fu_2689_p3;
wire   [2:0] num_1_6_fu_2696_p3;
wire   [3:0] num_1_6_cast_fu_2704_p1;
wire   [2:0] maxnum_2_6_fu_2681_p3;
wire   [0:0] tmp_112_7_fu_2714_p2;
wire   [0:0] sel_tmp15_fu_2728_p2;
wire   [0:0] sel_tmp16_fu_2733_p2;
wire   [2:0] maxnum_3_7_fu_2720_p3;
wire   [3:0] num_2_7_fu_2708_p2;
wire   [3:0] sel_tmp17_fu_2746_p3;
wire   [3:0] maxnum_2_7_cast1_cas_fu_2761_p1;
wire   [0:0] tmp_112_8_fu_2769_p2;
wire   [0:0] sel_tmp18_fu_2781_p2;
wire   [0:0] sel_tmp19_fu_2786_p2;
wire   [3:0] maxnum_3_8_fu_2774_p3;
wire   [3:0] num_2_8_fu_2764_p2;
wire   [3:0] sel_tmp20_fu_2799_p3;
wire   [3:0] num_1_8_fu_2806_p3;
wire   [3:0] maxnum_2_8_fu_2791_p3;
wire   [0:0] tmp_112_9_fu_2820_p2;
wire   [0:0] sel_tmp21_fu_2834_p2;
wire   [0:0] sel_tmp22_fu_2839_p2;
wire   [3:0] maxnum_3_9_fu_2826_p3;
wire   [3:0] num_2_9_fu_2814_p2;
wire   [3:0] sel_tmp23_fu_2852_p3;
wire   [3:0] num_1_9_fu_2859_p3;
wire   [3:0] maxnum_2_9_fu_2844_p3;
wire   [0:0] tmp_112_s_fu_2873_p2;
wire   [0:0] sel_tmp24_fu_2887_p2;
wire   [0:0] sel_tmp25_fu_2892_p2;
wire   [3:0] maxnum_3_s_fu_2879_p3;
wire   [3:0] num_2_s_fu_2867_p2;
wire   [3:0] sel_tmp26_fu_2905_p3;
wire   [0:0] tmp_112_1_fu_2925_p2;
wire   [0:0] sel_tmp27_fu_2935_p2;
wire   [0:0] sel_tmp28_fu_2940_p2;
wire   [3:0] maxnum_3_1_fu_2929_p3;
wire   [3:0] num_2_10_fu_2920_p2;
wire   [3:0] sel_tmp29_fu_2952_p3;
wire   [3:0] num_1_10_fu_2959_p3;
wire   [3:0] maxnum_2_10_fu_2945_p3;
wire   [0:0] tmp_112_10_fu_2973_p2;
wire   [0:0] sel_tmp30_fu_2987_p2;
wire   [0:0] sel_tmp31_fu_2992_p2;
wire   [3:0] maxnum_3_10_fu_2979_p3;
wire   [3:0] num_2_11_fu_2967_p2;
wire   [3:0] sel_tmp32_fu_3005_p3;
wire   [3:0] num_1_11_fu_3012_p3;
wire   [3:0] maxnum_2_11_fu_2997_p3;
wire   [0:0] tmp_112_11_fu_3026_p2;
wire   [0:0] sel_tmp33_fu_3040_p2;
wire   [0:0] sel_tmp34_fu_3045_p2;
wire   [3:0] maxnum_3_11_fu_3032_p3;
wire   [3:0] num_2_12_fu_3020_p2;
wire   [3:0] sel_tmp35_fu_3058_p3;
wire   [0:0] tmp_112_12_fu_3078_p2;
wire   [0:0] sel_tmp36_fu_3088_p2;
wire   [0:0] sel_tmp37_fu_3093_p2;
wire   [3:0] maxnum_3_12_fu_3082_p3;
wire   [3:0] num_2_13_fu_3073_p2;
wire   [3:0] sel_tmp38_fu_3105_p3;
wire   [3:0] num_1_13_fu_3112_p3;
wire   [4:0] num_1_13_cast_fu_3120_p1;
wire   [3:0] maxnum_2_13_fu_3098_p3;
wire   [0:0] tmp_112_13_fu_3130_p2;
wire   [0:0] sel_tmp39_fu_3144_p2;
wire   [0:0] sel_tmp40_fu_3149_p2;
wire   [3:0] maxnum_3_13_fu_3136_p3;
wire   [3:0] maxnum_2_14_fu_3154_p3;
wire   [4:0] num_2_14_fu_3124_p2;
wire   [4:0] sel_tmp41_fu_3166_p3;
wire   [4:0] maxnum_2_14_cast1_ca_fu_3162_p1;
wire   [4:0] num_1_14_fu_3173_p3;
wire   [0:0] tmp_55_fu_3181_p2;
wire   [4:0] maxnum_fu_3187_p3;
wire   [0:0] sel_tmp43_fu_3205_p2;
wire   [0:0] sel_tmp42_fu_3201_p2;
wire   [0:0] not_sel_tmp_fu_3209_p2;
wire   [7:0] grp_fu_3221_p0;
wire   [9:0] grp_fu_3221_p1;
wire   [7:0] grp_fu_3230_p0;
wire   [10:0] grp_fu_3230_p1;
wire   [7:0] grp_fu_3239_p0;
wire   [9:0] grp_fu_3239_p1;
wire   [7:0] grp_fu_3248_p0;
wire   [10:0] grp_fu_3248_p1;
wire   [7:0] grp_fu_3257_p0;
wire   [9:0] grp_fu_3257_p1;
wire   [7:0] grp_fu_3266_p0;
wire   [10:0] grp_fu_3266_p1;
wire   [7:0] grp_fu_3275_p0;
wire   [9:0] grp_fu_3275_p1;
wire   [7:0] grp_fu_3284_p0;
wire   [10:0] grp_fu_3284_p1;
wire   [7:0] grp_fu_3293_p0;
wire   [9:0] grp_fu_3293_p1;
wire   [7:0] grp_fu_3302_p0;
wire   [10:0] grp_fu_3302_p1;
wire   [7:0] grp_fu_3311_p0;
wire   [9:0] grp_fu_3311_p1;
wire   [7:0] grp_fu_3320_p0;
wire   [10:0] grp_fu_3320_p1;
wire   [7:0] grp_fu_3329_p0;
wire   [9:0] grp_fu_3329_p1;
wire   [7:0] grp_fu_3338_p0;
wire   [10:0] grp_fu_3338_p1;
wire   [7:0] grp_fu_3347_p0;
wire   [9:0] grp_fu_3347_p1;
wire   [7:0] grp_fu_3356_p0;
wire   [10:0] grp_fu_3356_p1;
wire   [7:0] grp_fu_3365_p0;
wire   [9:0] grp_fu_3365_p1;
wire   [7:0] grp_fu_3374_p0;
wire   [10:0] grp_fu_3374_p1;
wire   [7:0] grp_fu_3383_p0;
wire   [9:0] grp_fu_3383_p1;
wire   [7:0] grp_fu_3392_p0;
wire   [10:0] grp_fu_3392_p1;
wire   [7:0] grp_fu_3401_p0;
wire   [9:0] grp_fu_3401_p1;
wire   [7:0] grp_fu_3410_p0;
wire   [10:0] grp_fu_3410_p1;
wire   [7:0] grp_fu_3419_p0;
wire   [9:0] grp_fu_3419_p1;
wire   [7:0] grp_fu_3428_p0;
wire   [10:0] grp_fu_3428_p1;
wire   [7:0] grp_fu_3437_p0;
wire   [9:0] grp_fu_3437_p1;
wire   [7:0] grp_fu_3446_p0;
wire   [10:0] grp_fu_3446_p1;
wire   [7:0] grp_fu_3455_p0;
wire   [9:0] grp_fu_3455_p1;
wire   [7:0] grp_fu_3464_p0;
wire   [10:0] grp_fu_3464_p1;
wire   [7:0] grp_fu_3473_p0;
wire   [9:0] grp_fu_3473_p1;
wire   [7:0] grp_fu_3482_p0;
wire   [10:0] grp_fu_3482_p1;
wire   [7:0] grp_fu_3491_p0;
wire   [9:0] grp_fu_3491_p1;
wire   [7:0] grp_fu_3500_p0;
wire   [10:0] grp_fu_3500_p1;
wire   [7:0] grp_fu_3509_p0;
wire   [9:0] grp_fu_3509_p1;
wire   [7:0] grp_fu_3518_p0;
wire   [10:0] grp_fu_3518_p1;
wire   [0:0] p_0_fu_3215_p2;
reg    ap_ce_reg;
reg   [31:0] window_val_0_2_rea_int_reg;
reg   [31:0] window_val_0_3_rea_int_reg;
reg   [31:0] window_val_0_4_rea_int_reg;
reg   [31:0] window_val_1_1_rea_int_reg;
reg   [31:0] window_val_1_5_rea_int_reg;
reg   [31:0] window_val_2_0_rea_int_reg;
reg   [31:0] window_val_2_6_rea_int_reg;
reg   [31:0] window_val_3_0_rea_int_reg;
reg   [31:0] window_val_3_3_rea_int_reg;
reg   [31:0] window_val_3_6_rea_int_reg;
reg   [31:0] window_val_4_0_rea_int_reg;
reg   [31:0] window_val_4_6_rea_int_reg;
reg   [23:0] window_val_5_1_rea_int_reg;
reg   [23:0] window_val_5_5_rea_int_reg;
reg   [23:0] window_val_6_2_rea_int_reg;
reg   [23:0] window_val_6_3_rea_int_reg;
reg   [23:0] window_val_6_4_rea_int_reg;
reg   [8:0] threshold_data_int_reg;
reg   [0:0] ap_return_int_reg;
wire   [17:0] grp_fu_3221_p00;
wire   [18:0] grp_fu_3230_p00;
wire   [17:0] grp_fu_3239_p00;
wire   [18:0] grp_fu_3248_p00;
wire   [17:0] grp_fu_3257_p00;
wire   [18:0] grp_fu_3266_p00;
wire   [17:0] grp_fu_3275_p00;
wire   [18:0] grp_fu_3284_p00;
wire   [17:0] grp_fu_3293_p00;
wire   [18:0] grp_fu_3302_p00;
wire   [17:0] grp_fu_3311_p00;
wire   [18:0] grp_fu_3320_p00;
wire   [17:0] grp_fu_3329_p00;
wire   [18:0] grp_fu_3338_p00;
wire   [17:0] grp_fu_3347_p00;
wire   [18:0] grp_fu_3356_p00;
wire   [17:0] grp_fu_3365_p00;
wire   [18:0] grp_fu_3374_p00;
wire   [17:0] grp_fu_3383_p00;
wire   [18:0] grp_fu_3392_p00;
wire   [17:0] grp_fu_3401_p00;
wire   [18:0] grp_fu_3410_p00;
wire   [17:0] grp_fu_3419_p00;
wire   [18:0] grp_fu_3428_p00;
wire   [17:0] grp_fu_3437_p00;
wire   [18:0] grp_fu_3446_p00;
wire   [17:0] grp_fu_3455_p00;
wire   [18:0] grp_fu_3464_p00;
wire   [17:0] grp_fu_3473_p00;
wire   [18:0] grp_fu_3482_p00;
wire   [17:0] grp_fu_3491_p00;
wire   [18:0] grp_fu_3500_p00;
wire   [17:0] grp_fu_3509_p00;
wire   [18:0] grp_fu_3518_p00;

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U1(
    .din0(grp_fu_3221_p0),
    .din1(grp_fu_3221_p1),
    .din2(grp_fu_3230_p3),
    .dout(grp_fu_3221_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U2(
    .din0(grp_fu_3230_p0),
    .din1(grp_fu_3230_p1),
    .din2(tmp_6_fu_264_p2),
    .dout(grp_fu_3230_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U3(
    .din0(grp_fu_3239_p0),
    .din1(grp_fu_3239_p1),
    .din2(grp_fu_3248_p3),
    .dout(grp_fu_3239_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U4(
    .din0(grp_fu_3248_p0),
    .din1(grp_fu_3248_p1),
    .din2(tmp_1_fu_342_p2),
    .dout(grp_fu_3248_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U5(
    .din0(grp_fu_3257_p0),
    .din1(grp_fu_3257_p1),
    .din2(grp_fu_3266_p3),
    .dout(grp_fu_3257_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U6(
    .din0(grp_fu_3266_p0),
    .din1(grp_fu_3266_p1),
    .din2(tmp_14_fu_420_p2),
    .dout(grp_fu_3266_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U7(
    .din0(grp_fu_3275_p0),
    .din1(grp_fu_3275_p1),
    .din2(grp_fu_3284_p3),
    .dout(grp_fu_3275_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U8(
    .din0(grp_fu_3284_p0),
    .din1(grp_fu_3284_p1),
    .din2(tmp_22_fu_498_p2),
    .dout(grp_fu_3284_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U9(
    .din0(grp_fu_3293_p0),
    .din1(grp_fu_3293_p1),
    .din2(grp_fu_3302_p3),
    .dout(grp_fu_3293_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U10(
    .din0(grp_fu_3302_p0),
    .din1(grp_fu_3302_p1),
    .din2(tmp_28_fu_576_p2),
    .dout(grp_fu_3302_p3)
);

image_sobel_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 18 ))
image_sobel_mac_mdEe_U11(
    .din0(grp_fu_3311_p0),
    .din1(grp_fu_3311_p1),
    .din2(tmp_105_1_fu_654_p2),
    .dout(grp_fu_3311_p3)
);

image_sobel_mac_meOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_meOg_U12(
    .din0(grp_fu_3320_p0),
    .din1(grp_fu_3320_p1),
    .din2(grp_fu_3311_p3),
    .dout(grp_fu_3320_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U13(
    .din0(grp_fu_3329_p0),
    .din1(grp_fu_3329_p1),
    .din2(grp_fu_3338_p3),
    .dout(grp_fu_3329_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U14(
    .din0(grp_fu_3338_p0),
    .din1(grp_fu_3338_p1),
    .din2(tmp_105_2_fu_732_p2),
    .dout(grp_fu_3338_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U15(
    .din0(grp_fu_3347_p0),
    .din1(grp_fu_3347_p1),
    .din2(grp_fu_3356_p3),
    .dout(grp_fu_3347_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U16(
    .din0(grp_fu_3356_p0),
    .din1(grp_fu_3356_p1),
    .din2(tmp_105_3_fu_810_p2),
    .dout(grp_fu_3356_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U17(
    .din0(grp_fu_3365_p0),
    .din1(grp_fu_3365_p1),
    .din2(grp_fu_3374_p3),
    .dout(grp_fu_3365_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U18(
    .din0(grp_fu_3374_p0),
    .din1(grp_fu_3374_p1),
    .din2(tmp_105_5_fu_888_p2),
    .dout(grp_fu_3374_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U19(
    .din0(grp_fu_3383_p0),
    .din1(grp_fu_3383_p1),
    .din2(grp_fu_3392_p3),
    .dout(grp_fu_3383_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U20(
    .din0(grp_fu_3392_p0),
    .din1(grp_fu_3392_p1),
    .din2(tmp_105_6_fu_966_p2),
    .dout(grp_fu_3392_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U21(
    .din0(grp_fu_3401_p0),
    .din1(grp_fu_3401_p1),
    .din2(grp_fu_3410_p3),
    .dout(grp_fu_3401_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U22(
    .din0(grp_fu_3410_p0),
    .din1(grp_fu_3410_p1),
    .din2(tmp_105_7_fu_1044_p2),
    .dout(grp_fu_3410_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U23(
    .din0(grp_fu_3419_p0),
    .din1(grp_fu_3419_p1),
    .din2(grp_fu_3428_p3),
    .dout(grp_fu_3419_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U24(
    .din0(grp_fu_3428_p0),
    .din1(grp_fu_3428_p1),
    .din2(tmp_105_9_fu_1122_p2),
    .dout(grp_fu_3428_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U25(
    .din0(grp_fu_3437_p0),
    .din1(grp_fu_3437_p1),
    .din2(grp_fu_3446_p3),
    .dout(grp_fu_3437_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U26(
    .din0(grp_fu_3446_p0),
    .din1(grp_fu_3446_p1),
    .din2(tmp_105_s_fu_1200_p2),
    .dout(grp_fu_3446_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U27(
    .din0(grp_fu_3455_p0),
    .din1(grp_fu_3455_p1),
    .din2(grp_fu_3464_p3),
    .dout(grp_fu_3455_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U28(
    .din0(grp_fu_3464_p0),
    .din1(grp_fu_3464_p1),
    .din2(tmp_105_4_fu_1278_p2),
    .dout(grp_fu_3464_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U29(
    .din0(grp_fu_3473_p0),
    .din1(grp_fu_3473_p1),
    .din2(grp_fu_3482_p3),
    .dout(grp_fu_3473_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U30(
    .din0(grp_fu_3482_p0),
    .din1(grp_fu_3482_p1),
    .din2(tmp_105_8_fu_1356_p2),
    .dout(grp_fu_3482_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U31(
    .din0(grp_fu_3491_p0),
    .din1(grp_fu_3491_p1),
    .din2(grp_fu_3500_p3),
    .dout(grp_fu_3491_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U32(
    .din0(grp_fu_3500_p0),
    .din1(grp_fu_3500_p1),
    .din2(tmp_105_10_fu_1434_p2),
    .dout(grp_fu_3500_p3)
);

image_sobel_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
image_sobel_mac_mbkb_U33(
    .din0(grp_fu_3509_p0),
    .din1(grp_fu_3509_p1),
    .din2(grp_fu_3518_p3),
    .dout(grp_fu_3509_p3)
);

image_sobel_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
image_sobel_mac_mcud_U34(
    .din0(grp_fu_3518_p0),
    .din1(grp_fu_3518_p1),
    .din2(tmp_105_11_fu_1512_p2),
    .dout(grp_fu_3518_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= p_0_fu_3215_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        icmp_reg_3754 <= icmp_fu_2403_p2;
        icmp_reg_3754_pp0_iter3_reg <= icmp_reg_3754;
        icmp_reg_3754_pp0_iter4_reg <= icmp_reg_3754_pp0_iter3_reg;
        icmp_reg_3754_pp0_iter5_reg <= icmp_reg_3754_pp0_iter4_reg;
        icmp_reg_3754_pp0_iter6_reg <= icmp_reg_3754_pp0_iter5_reg;
        maxnum_2_12_reg_3799 <= maxnum_2_12_fu_3050_p3;
        maxnum_2_4_reg_3759 <= maxnum_2_4_fu_2581_p3;
        maxnum_2_7_reg_3773 <= maxnum_2_7_fu_2738_p3;
        maxnum_2_s_reg_3785 <= maxnum_2_s_fu_2897_p3;
        num_1_12_reg_3806 <= num_1_12_fu_3065_p3;
        num_1_4_reg_3766 <= num_1_4_fu_2596_p3;
        num_1_7_reg_3778 <= num_1_7_fu_2753_p3;
        num_1_s_reg_3792 <= num_1_s_fu_2912_p3;
        threshold_data_read_reg_3527 <= threshold_data_int_reg;
        tmp_10_reg_3537 <= {{grp_fu_3239_p3[19:8]}};
        tmp_111_10_reg_3720 <= tmp_111_10_fu_2173_p2;
        tmp_111_10_reg_3720_pp0_iter2_reg <= tmp_111_10_reg_3720;
        tmp_111_10_reg_3720_pp0_iter3_reg <= tmp_111_10_reg_3720_pp0_iter2_reg;
        tmp_111_10_reg_3720_pp0_iter4_reg <= tmp_111_10_reg_3720_pp0_iter3_reg;
        tmp_111_11_reg_3727 <= tmp_111_11_fu_2205_p2;
        tmp_111_11_reg_3727_pp0_iter2_reg <= tmp_111_11_reg_3727;
        tmp_111_11_reg_3727_pp0_iter3_reg <= tmp_111_11_reg_3727_pp0_iter2_reg;
        tmp_111_11_reg_3727_pp0_iter4_reg <= tmp_111_11_reg_3727_pp0_iter3_reg;
        tmp_111_12_reg_3734 <= tmp_111_12_fu_2244_p2;
        tmp_111_12_reg_3734_pp0_iter2_reg <= tmp_111_12_reg_3734;
        tmp_111_12_reg_3734_pp0_iter3_reg <= tmp_111_12_reg_3734_pp0_iter2_reg;
        tmp_111_12_reg_3734_pp0_iter4_reg <= tmp_111_12_reg_3734_pp0_iter3_reg;
        tmp_111_12_reg_3734_pp0_iter5_reg <= tmp_111_12_reg_3734_pp0_iter4_reg;
        tmp_111_13_reg_3741 <= tmp_111_13_fu_2283_p2;
        tmp_111_13_reg_3741_pp0_iter2_reg <= tmp_111_13_reg_3741;
        tmp_111_13_reg_3741_pp0_iter3_reg <= tmp_111_13_reg_3741_pp0_iter2_reg;
        tmp_111_13_reg_3741_pp0_iter4_reg <= tmp_111_13_reg_3741_pp0_iter3_reg;
        tmp_111_13_reg_3741_pp0_iter5_reg <= tmp_111_13_reg_3741_pp0_iter4_reg;
        tmp_111_14_reg_3748 <= tmp_111_14_fu_2322_p2;
        tmp_111_14_reg_3748_pp0_iter2_reg <= tmp_111_14_reg_3748;
        tmp_111_14_reg_3748_pp0_iter3_reg <= tmp_111_14_reg_3748_pp0_iter2_reg;
        tmp_111_14_reg_3748_pp0_iter4_reg <= tmp_111_14_reg_3748_pp0_iter3_reg;
        tmp_111_14_reg_3748_pp0_iter5_reg <= tmp_111_14_reg_3748_pp0_iter4_reg;
        tmp_111_1_reg_3650 <= tmp_111_1_fu_1797_p2;
        tmp_111_2_reg_3657 <= tmp_111_2_fu_1836_p2;
        tmp_111_3_reg_3664 <= tmp_111_3_fu_1875_p2;
        tmp_111_4_reg_3671 <= tmp_111_4_fu_1907_p2;
        tmp_111_4_reg_3671_pp0_iter2_reg <= tmp_111_4_reg_3671;
        tmp_111_5_reg_3678 <= tmp_111_5_fu_1946_p2;
        tmp_111_5_reg_3678_pp0_iter2_reg <= tmp_111_5_reg_3678;
        tmp_111_6_reg_3685 <= tmp_111_6_fu_1985_p2;
        tmp_111_6_reg_3685_pp0_iter2_reg <= tmp_111_6_reg_3685;
        tmp_111_7_reg_3692 <= tmp_111_7_fu_2024_p2;
        tmp_111_7_reg_3692_pp0_iter2_reg <= tmp_111_7_reg_3692;
        tmp_111_7_reg_3692_pp0_iter3_reg <= tmp_111_7_reg_3692_pp0_iter2_reg;
        tmp_111_8_reg_3699 <= tmp_111_8_fu_2056_p2;
        tmp_111_8_reg_3699_pp0_iter2_reg <= tmp_111_8_reg_3699;
        tmp_111_8_reg_3699_pp0_iter3_reg <= tmp_111_8_reg_3699_pp0_iter2_reg;
        tmp_111_9_reg_3706 <= tmp_111_9_fu_2095_p2;
        tmp_111_9_reg_3706_pp0_iter2_reg <= tmp_111_9_reg_3706;
        tmp_111_9_reg_3706_pp0_iter3_reg <= tmp_111_9_reg_3706_pp0_iter2_reg;
        tmp_111_s_reg_3713 <= tmp_111_s_fu_2134_p2;
        tmp_111_s_reg_3713_pp0_iter2_reg <= tmp_111_s_reg_3713;
        tmp_111_s_reg_3713_pp0_iter3_reg <= tmp_111_s_reg_3713_pp0_iter2_reg;
        tmp_111_s_reg_3713_pp0_iter4_reg <= tmp_111_s_reg_3713_pp0_iter3_reg;
        tmp_16_reg_3542 <= {{grp_fu_3257_p3[19:8]}};
        tmp_18_reg_3617 <= tmp_18_fu_1580_p2;
        tmp_18_reg_3617_pp0_iter2_reg <= tmp_18_reg_3617;
        tmp_18_reg_3617_pp0_iter3_reg <= tmp_18_reg_3617_pp0_iter2_reg;
        tmp_18_reg_3617_pp0_iter4_reg <= tmp_18_reg_3617_pp0_iter3_reg;
        tmp_18_reg_3617_pp0_iter5_reg <= tmp_18_reg_3617_pp0_iter4_reg;
        tmp_18_reg_3617_pp0_iter6_reg <= tmp_18_reg_3617_pp0_iter5_reg;
        tmp_24_reg_3547 <= {{grp_fu_3275_p3[19:8]}};
        tmp_30_reg_3552 <= {{grp_fu_3293_p3[19:8]}};
        tmp_32_reg_3623 <= tmp_32_fu_1622_p2;
        tmp_34_reg_3629 <= tmp_34_fu_1654_p2;
        tmp_36_reg_3634 <= tmp_36_fu_1690_p2;
        tmp_38_reg_3639 <= tmp_38_fu_1726_p2;
        tmp_44_reg_3644 <= tmp_44_fu_1758_p2;
        tmp_47_reg_3557 <= {{grp_fu_3320_p3[19:8]}};
        tmp_51_reg_3562 <= {{grp_fu_3329_p3[19:8]}};
        tmp_56_reg_3567 <= {{grp_fu_3347_p3[19:8]}};
        tmp_59_reg_3813 <= tmp_59_fu_3195_p2;
        tmp_5_reg_3532 <= {{grp_fu_3221_p3[19:8]}};
        tmp_61_reg_3572 <= {{grp_fu_3365_p3[19:8]}};
        tmp_65_reg_3577 <= {{grp_fu_3383_p3[19:8]}};
        tmp_69_reg_3582 <= {{grp_fu_3401_p3[19:8]}};
        tmp_73_reg_3587 <= {{grp_fu_3419_p3[19:8]}};
        tmp_77_reg_3592 <= {{grp_fu_3437_p3[19:8]}};
        tmp_81_reg_3597 <= {{grp_fu_3455_p3[19:8]}};
        tmp_85_reg_3602 <= {{grp_fu_3473_p3[19:8]}};
        tmp_89_reg_3607 <= {{grp_fu_3491_p3[19:8]}};
        tmp_93_reg_3612 <= {{grp_fu_3509_p3[19:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        threshold_data_int_reg <= threshold_data;
        window_val_0_2_rea_int_reg <= window_val_0_2_rea;
        window_val_0_3_rea_int_reg <= window_val_0_3_rea;
        window_val_0_4_rea_int_reg <= window_val_0_4_rea;
        window_val_1_1_rea_int_reg <= window_val_1_1_rea;
        window_val_1_5_rea_int_reg <= window_val_1_5_rea;
        window_val_2_0_rea_int_reg <= window_val_2_0_rea;
        window_val_2_6_rea_int_reg <= window_val_2_6_rea;
        window_val_3_0_rea_int_reg <= window_val_3_0_rea;
        window_val_3_3_rea_int_reg <= window_val_3_3_rea;
        window_val_3_6_rea_int_reg <= window_val_3_6_rea;
        window_val_4_0_rea_int_reg <= window_val_4_0_rea;
        window_val_4_6_rea_int_reg <= window_val_4_6_rea;
        window_val_5_1_rea_int_reg <= window_val_5_1_rea;
        window_val_5_5_rea_int_reg <= window_val_5_5_rea;
        window_val_6_2_rea_int_reg <= window_val_6_2_rea;
        window_val_6_3_rea_int_reg <= window_val_6_3_rea;
        window_val_6_4_rea_int_reg <= window_val_6_4_rea;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = p_0_fu_3215_p2;
    end
end

assign G_1_fu_290_p4 = {{window_val_6_3_rea_int_reg[15:8]}};

assign G_2_fu_368_p4 = {{window_val_0_3_rea_int_reg[15:8]}};

assign G_3_fu_446_p4 = {{window_val_3_6_rea_int_reg[15:8]}};

assign G_4_fu_524_p4 = {{window_val_3_0_rea_int_reg[15:8]}};

assign G_5_10_fu_1382_p4 = {{window_val_1_1_rea_int_reg[15:8]}};

assign G_5_11_fu_1460_p4 = {{window_val_0_2_rea_int_reg[15:8]}};

assign G_5_1_fu_602_p4 = {{window_val_0_4_rea_int_reg[15:8]}};

assign G_5_2_fu_680_p4 = {{window_val_1_5_rea_int_reg[15:8]}};

assign G_5_3_fu_758_p4 = {{window_val_2_6_rea_int_reg[15:8]}};

assign G_5_4_fu_1226_p4 = {{window_val_4_0_rea_int_reg[15:8]}};

assign G_5_5_fu_836_p4 = {{window_val_4_6_rea_int_reg[15:8]}};

assign G_5_6_fu_914_p4 = {{window_val_5_5_rea_int_reg[15:8]}};

assign G_5_7_fu_992_p4 = {{window_val_6_4_rea_int_reg[15:8]}};

assign G_5_8_fu_1304_p4 = {{window_val_2_0_rea_int_reg[15:8]}};

assign G_5_9_fu_1070_p4 = {{window_val_6_2_rea_int_reg[15:8]}};

assign G_5_s_fu_1148_p4 = {{window_val_5_1_rea_int_reg[15:8]}};

assign G_fu_212_p4 = {{window_val_3_3_rea_int_reg[15:8]}};

assign R_1_fu_286_p1 = window_val_6_3_rea_int_reg[7:0];

assign R_2_fu_364_p1 = window_val_0_3_rea_int_reg[7:0];

assign R_3_fu_442_p1 = window_val_3_6_rea_int_reg[7:0];

assign R_4_fu_520_p1 = window_val_3_0_rea_int_reg[7:0];

assign R_fu_208_p1 = window_val_3_3_rea_int_reg[7:0];

assign abs1_fu_1614_p3 = ((abscond1_fu_1608_p2[0:0] === 1'b1) ? tmp_31_fu_1596_p2 : neg1_fu_1602_p2);

assign abs2_fu_1646_p3 = ((abscond2_fu_1640_p2[0:0] === 1'b1) ? tmp_33_fu_1628_p2 : neg2_fu_1634_p2);

assign abs3_fu_1682_p3 = ((abscond3_fu_1676_p2[0:0] === 1'b1) ? tmp_35_fu_1664_p2 : neg3_fu_1670_p2);

assign abs4_fu_1718_p3 = ((abscond4_fu_1712_p2[0:0] === 1'b1) ? tmp_37_fu_1700_p2 : neg4_fu_1706_p2);

assign abs5_10_fu_2165_p3 = ((abscond5_10_fu_2159_p2[0:0] === 1'b1) ? tmp_110_10_fu_2147_p2 : neg5_10_fu_2153_p2);

assign abs5_11_fu_2197_p3 = ((abscond5_11_fu_2191_p2[0:0] === 1'b1) ? tmp_110_11_fu_2179_p2 : neg5_11_fu_2185_p2);

assign abs5_12_fu_2236_p3 = ((abscond5_12_fu_2230_p2[0:0] === 1'b1) ? tmp_110_12_fu_2218_p2 : neg5_12_fu_2224_p2);

assign abs5_13_fu_2275_p3 = ((abscond5_13_fu_2269_p2[0:0] === 1'b1) ? tmp_110_13_fu_2257_p2 : neg5_13_fu_2263_p2);

assign abs5_14_fu_2314_p3 = ((abscond5_14_fu_2308_p2[0:0] === 1'b1) ? tmp_110_14_fu_2296_p2 : neg5_14_fu_2302_p2);

assign abs5_1_fu_1789_p3 = ((abscond5_1_fu_1783_p2[0:0] === 1'b1) ? tmp_110_1_fu_1771_p2 : neg5_1_fu_1777_p2);

assign abs5_2_fu_1828_p3 = ((abscond5_2_fu_1822_p2[0:0] === 1'b1) ? tmp_110_2_fu_1810_p2 : neg5_2_fu_1816_p2);

assign abs5_3_fu_1867_p3 = ((abscond5_3_fu_1861_p2[0:0] === 1'b1) ? tmp_110_3_fu_1849_p2 : neg5_3_fu_1855_p2);

assign abs5_4_fu_1899_p3 = ((abscond5_4_fu_1893_p2[0:0] === 1'b1) ? tmp_110_4_fu_1881_p2 : neg5_4_fu_1887_p2);

assign abs5_5_fu_1938_p3 = ((abscond5_5_fu_1932_p2[0:0] === 1'b1) ? tmp_110_5_fu_1920_p2 : neg5_5_fu_1926_p2);

assign abs5_6_fu_1977_p3 = ((abscond5_6_fu_1971_p2[0:0] === 1'b1) ? tmp_110_6_fu_1959_p2 : neg5_6_fu_1965_p2);

assign abs5_7_fu_2016_p3 = ((abscond5_7_fu_2010_p2[0:0] === 1'b1) ? tmp_110_7_fu_1998_p2 : neg5_7_fu_2004_p2);

assign abs5_8_fu_2048_p3 = ((abscond5_8_fu_2042_p2[0:0] === 1'b1) ? tmp_110_8_fu_2030_p2 : neg5_8_fu_2036_p2);

assign abs5_9_fu_2087_p3 = ((abscond5_9_fu_2081_p2[0:0] === 1'b1) ? tmp_110_9_fu_2069_p2 : neg5_9_fu_2075_p2);

assign abs5_fu_1750_p3 = ((abscond5_fu_1744_p2[0:0] === 1'b1) ? tmp_43_fu_1732_p2 : neg5_fu_1738_p2);

assign abs5_s_fu_2126_p3 = ((abscond5_s_fu_2120_p2[0:0] === 1'b1) ? tmp_110_s_fu_2108_p2 : neg5_s_fu_2114_p2);

assign abs_fu_1569_p3 = ((abscond_fu_1563_p2[0:0] === 1'b1) ? tmp_17_fu_1551_p2 : neg_fu_1557_p2);

assign abscond1_fu_1608_p2 = (($signed(tmp_31_fu_1596_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond2_fu_1640_p2 = (($signed(tmp_33_fu_1628_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond3_fu_1676_p2 = (($signed(tmp_35_fu_1664_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond4_fu_1712_p2 = (($signed(tmp_37_fu_1700_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_10_fu_2159_p2 = (($signed(tmp_110_10_fu_2147_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_11_fu_2191_p2 = (($signed(tmp_110_11_fu_2179_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_12_fu_2230_p2 = (($signed(tmp_110_12_fu_2218_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_13_fu_2269_p2 = (($signed(tmp_110_13_fu_2257_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_14_fu_2308_p2 = (($signed(tmp_110_14_fu_2296_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_1_fu_1783_p2 = (($signed(tmp_110_1_fu_1771_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_2_fu_1822_p2 = (($signed(tmp_110_2_fu_1810_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_3_fu_1861_p2 = (($signed(tmp_110_3_fu_1849_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_4_fu_1893_p2 = (($signed(tmp_110_4_fu_1881_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_5_fu_1932_p2 = (($signed(tmp_110_5_fu_1920_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_6_fu_1971_p2 = (($signed(tmp_110_6_fu_1959_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_7_fu_2010_p2 = (($signed(tmp_110_7_fu_1998_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_8_fu_2042_p2 = (($signed(tmp_110_8_fu_2030_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_9_fu_2081_p2 = (($signed(tmp_110_9_fu_2069_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_fu_1744_p2 = (($signed(tmp_43_fu_1732_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond5_s_fu_2120_p2 = (($signed(tmp_110_s_fu_2108_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_1563_p2 = (($signed(tmp_17_fu_1551_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign grp_fu_3221_p0 = grp_fu_3221_p00;

assign grp_fu_3221_p00 = R_fu_208_p1;

assign grp_fu_3221_p1 = 18'd305;

assign grp_fu_3230_p0 = grp_fu_3230_p00;

assign grp_fu_3230_p00 = G_fu_212_p4;

assign grp_fu_3230_p1 = 19'd599;

assign grp_fu_3239_p0 = grp_fu_3239_p00;

assign grp_fu_3239_p00 = R_1_fu_286_p1;

assign grp_fu_3239_p1 = 18'd305;

assign grp_fu_3248_p0 = grp_fu_3248_p00;

assign grp_fu_3248_p00 = G_1_fu_290_p4;

assign grp_fu_3248_p1 = 19'd599;

assign grp_fu_3257_p0 = grp_fu_3257_p00;

assign grp_fu_3257_p00 = R_2_fu_364_p1;

assign grp_fu_3257_p1 = 18'd305;

assign grp_fu_3266_p0 = grp_fu_3266_p00;

assign grp_fu_3266_p00 = G_2_fu_368_p4;

assign grp_fu_3266_p1 = 19'd599;

assign grp_fu_3275_p0 = grp_fu_3275_p00;

assign grp_fu_3275_p00 = R_3_fu_442_p1;

assign grp_fu_3275_p1 = 18'd305;

assign grp_fu_3284_p0 = grp_fu_3284_p00;

assign grp_fu_3284_p00 = G_3_fu_446_p4;

assign grp_fu_3284_p1 = 19'd599;

assign grp_fu_3293_p0 = grp_fu_3293_p00;

assign grp_fu_3293_p00 = R_4_fu_520_p1;

assign grp_fu_3293_p1 = 18'd305;

assign grp_fu_3302_p0 = grp_fu_3302_p00;

assign grp_fu_3302_p00 = G_4_fu_524_p4;

assign grp_fu_3302_p1 = 19'd599;

assign grp_fu_3311_p0 = grp_fu_3311_p00;

assign grp_fu_3311_p00 = tmp_45_fu_598_p1;

assign grp_fu_3311_p1 = 18'd305;

assign grp_fu_3320_p0 = grp_fu_3320_p00;

assign grp_fu_3320_p00 = G_5_1_fu_602_p4;

assign grp_fu_3320_p1 = 19'd599;

assign grp_fu_3329_p0 = grp_fu_3329_p00;

assign grp_fu_3329_p00 = tmp_49_fu_676_p1;

assign grp_fu_3329_p1 = 18'd305;

assign grp_fu_3338_p0 = grp_fu_3338_p00;

assign grp_fu_3338_p00 = G_5_2_fu_680_p4;

assign grp_fu_3338_p1 = 19'd599;

assign grp_fu_3347_p0 = grp_fu_3347_p00;

assign grp_fu_3347_p00 = tmp_53_fu_754_p1;

assign grp_fu_3347_p1 = 18'd305;

assign grp_fu_3356_p0 = grp_fu_3356_p00;

assign grp_fu_3356_p00 = G_5_3_fu_758_p4;

assign grp_fu_3356_p1 = 19'd599;

assign grp_fu_3365_p0 = grp_fu_3365_p00;

assign grp_fu_3365_p00 = tmp_58_fu_832_p1;

assign grp_fu_3365_p1 = 18'd305;

assign grp_fu_3374_p0 = grp_fu_3374_p00;

assign grp_fu_3374_p00 = G_5_5_fu_836_p4;

assign grp_fu_3374_p1 = 19'd599;

assign grp_fu_3383_p0 = grp_fu_3383_p00;

assign grp_fu_3383_p00 = tmp_63_fu_910_p1;

assign grp_fu_3383_p1 = 18'd305;

assign grp_fu_3392_p0 = grp_fu_3392_p00;

assign grp_fu_3392_p00 = G_5_6_fu_914_p4;

assign grp_fu_3392_p1 = 19'd599;

assign grp_fu_3401_p0 = grp_fu_3401_p00;

assign grp_fu_3401_p00 = tmp_67_fu_988_p1;

assign grp_fu_3401_p1 = 18'd305;

assign grp_fu_3410_p0 = grp_fu_3410_p00;

assign grp_fu_3410_p00 = G_5_7_fu_992_p4;

assign grp_fu_3410_p1 = 19'd599;

assign grp_fu_3419_p0 = grp_fu_3419_p00;

assign grp_fu_3419_p00 = tmp_71_fu_1066_p1;

assign grp_fu_3419_p1 = 18'd305;

assign grp_fu_3428_p0 = grp_fu_3428_p00;

assign grp_fu_3428_p00 = G_5_9_fu_1070_p4;

assign grp_fu_3428_p1 = 19'd599;

assign grp_fu_3437_p0 = grp_fu_3437_p00;

assign grp_fu_3437_p00 = tmp_75_fu_1144_p1;

assign grp_fu_3437_p1 = 18'd305;

assign grp_fu_3446_p0 = grp_fu_3446_p00;

assign grp_fu_3446_p00 = G_5_s_fu_1148_p4;

assign grp_fu_3446_p1 = 19'd599;

assign grp_fu_3455_p0 = grp_fu_3455_p00;

assign grp_fu_3455_p00 = tmp_79_fu_1222_p1;

assign grp_fu_3455_p1 = 18'd305;

assign grp_fu_3464_p0 = grp_fu_3464_p00;

assign grp_fu_3464_p00 = G_5_4_fu_1226_p4;

assign grp_fu_3464_p1 = 19'd599;

assign grp_fu_3473_p0 = grp_fu_3473_p00;

assign grp_fu_3473_p00 = tmp_83_fu_1300_p1;

assign grp_fu_3473_p1 = 18'd305;

assign grp_fu_3482_p0 = grp_fu_3482_p00;

assign grp_fu_3482_p00 = G_5_8_fu_1304_p4;

assign grp_fu_3482_p1 = 19'd599;

assign grp_fu_3491_p0 = grp_fu_3491_p00;

assign grp_fu_3491_p00 = tmp_87_fu_1378_p1;

assign grp_fu_3491_p1 = 18'd305;

assign grp_fu_3500_p0 = grp_fu_3500_p00;

assign grp_fu_3500_p00 = G_5_10_fu_1382_p4;

assign grp_fu_3500_p1 = 19'd599;

assign grp_fu_3509_p0 = grp_fu_3509_p00;

assign grp_fu_3509_p00 = tmp_91_fu_1456_p1;

assign grp_fu_3509_p1 = 18'd305;

assign grp_fu_3518_p0 = grp_fu_3518_p00;

assign grp_fu_3518_p00 = G_5_11_fu_1460_p4;

assign grp_fu_3518_p1 = 19'd599;

assign icmp_fu_2403_p2 = ((tmp_42_fu_2396_p3 != 2'd0) ? 1'b1 : 1'b0);

assign k_1_cast_fu_2364_p1 = k_1_s_fu_2357_p3;

assign k_1_fu_2344_p3 = ((tmp_34_reg_3629[0:0] === 1'b1) ? p_cast_fu_2333_p1 : k_fu_2337_p3);

assign k_1_s_fu_2357_p3 = ((tmp_36_reg_3634[0:0] === 1'b1) ? k_1_fu_2344_p3 : k_2_fu_2351_p2);

assign k_2_fu_2351_p2 = (k_1_fu_2344_p3 + 2'd1);

assign k_3_fu_2368_p2 = (k_1_cast_fu_2364_p1 + 3'd1);

assign k_fu_2337_p3 = ((tmp_32_reg_3623[0:0] === 1'b1) ? 2'd1 : 2'd2);

assign maxnum_2_10_fu_2945_p3 = ((sel_tmp28_fu_2940_p2[0:0] === 1'b1) ? maxnum_3_1_fu_2929_p3 : maxnum_2_s_reg_3785);

assign maxnum_2_11_fu_2997_p3 = ((sel_tmp31_fu_2992_p2[0:0] === 1'b1) ? maxnum_3_10_fu_2979_p3 : maxnum_2_10_fu_2945_p3);

assign maxnum_2_12_fu_3050_p3 = ((sel_tmp34_fu_3045_p2[0:0] === 1'b1) ? maxnum_3_11_fu_3032_p3 : maxnum_2_11_fu_2997_p3);

assign maxnum_2_13_fu_3098_p3 = ((sel_tmp37_fu_3093_p2[0:0] === 1'b1) ? maxnum_3_12_fu_3082_p3 : maxnum_2_12_reg_3799);

assign maxnum_2_14_cast1_ca_fu_3162_p1 = maxnum_2_14_fu_3154_p3;

assign maxnum_2_14_fu_3154_p3 = ((sel_tmp40_fu_3149_p2[0:0] === 1'b1) ? maxnum_3_13_fu_3136_p3 : maxnum_2_13_fu_3098_p3);

assign maxnum_2_1_cast_fu_2426_p1 = maxnum_2_1_fu_2421_p2;

assign maxnum_2_1_fu_2421_p2 = (tmp_44_reg_3644 & not_tmp_111_1_fu_2416_p2);

assign maxnum_2_2_fu_2467_p3 = ((sel_tmp6_fu_2462_p2[0:0] === 1'b1) ? maxnum_3_2_fu_2449_p3 : maxnum_2_1_cast_fu_2426_p1);

assign maxnum_2_3_cast1_cas_fu_2532_p1 = maxnum_2_3_fu_2524_p3;

assign maxnum_2_3_fu_2524_p3 = ((sel_tmp1_fu_2519_p2[0:0] === 1'b1) ? maxnum_3_3_fu_2506_p3 : maxnum_2_2_fu_2467_p3);

assign maxnum_2_4_fu_2581_p3 = ((sel_tmp4_fu_2576_p2[0:0] === 1'b1) ? maxnum_3_4_fu_2563_p3 : maxnum_2_3_cast1_cas_fu_2532_p1);

assign maxnum_2_5_fu_2629_p3 = ((sel_tmp10_fu_2624_p2[0:0] === 1'b1) ? maxnum_3_5_fu_2613_p3 : maxnum_2_4_reg_3759);

assign maxnum_2_6_fu_2681_p3 = ((sel_tmp13_fu_2676_p2[0:0] === 1'b1) ? maxnum_3_6_fu_2663_p3 : maxnum_2_5_fu_2629_p3);

assign maxnum_2_7_cast1_cas_fu_2761_p1 = maxnum_2_7_reg_3773;

assign maxnum_2_7_fu_2738_p3 = ((sel_tmp16_fu_2733_p2[0:0] === 1'b1) ? maxnum_3_7_fu_2720_p3 : maxnum_2_6_fu_2681_p3);

assign maxnum_2_8_fu_2791_p3 = ((sel_tmp19_fu_2786_p2[0:0] === 1'b1) ? maxnum_3_8_fu_2774_p3 : maxnum_2_7_cast1_cas_fu_2761_p1);

assign maxnum_2_9_fu_2844_p3 = ((sel_tmp22_fu_2839_p2[0:0] === 1'b1) ? maxnum_3_9_fu_2826_p3 : maxnum_2_8_fu_2791_p3);

assign maxnum_2_s_fu_2897_p3 = ((sel_tmp25_fu_2892_p2[0:0] === 1'b1) ? maxnum_3_s_fu_2879_p3 : maxnum_2_9_fu_2844_p3);

assign maxnum_3_10_fu_2979_p3 = ((tmp_112_10_fu_2973_p2[0:0] === 1'b1) ? maxnum_2_10_fu_2945_p3 : num_1_10_fu_2959_p3);

assign maxnum_3_11_fu_3032_p3 = ((tmp_112_11_fu_3026_p2[0:0] === 1'b1) ? maxnum_2_11_fu_2997_p3 : num_1_11_fu_3012_p3);

assign maxnum_3_12_fu_3082_p3 = ((tmp_112_12_fu_3078_p2[0:0] === 1'b1) ? maxnum_2_12_reg_3799 : num_1_12_reg_3806);

assign maxnum_3_13_fu_3136_p3 = ((tmp_112_13_fu_3130_p2[0:0] === 1'b1) ? maxnum_2_13_fu_3098_p3 : num_1_13_fu_3112_p3);

assign maxnum_3_1_fu_2929_p3 = ((tmp_112_1_fu_2925_p2[0:0] === 1'b1) ? maxnum_2_s_reg_3785 : num_1_s_reg_3792);

assign maxnum_3_2_fu_2449_p3 = ((tmp_112_2_fu_2443_p2[0:0] === 1'b1) ? maxnum_2_1_cast_fu_2426_p1 : num_1_1_fu_2430_p3);

assign maxnum_3_3_fu_2506_p3 = ((tmp_112_3_fu_2500_p2[0:0] === 1'b1) ? maxnum_2_2_fu_2467_p3 : num_1_2_fu_2482_p3);

assign maxnum_3_4_fu_2563_p3 = ((tmp_112_4_fu_2557_p2[0:0] === 1'b1) ? maxnum_2_3_cast1_cas_fu_2532_p1 : num_1_3_fu_2543_p3);

assign maxnum_3_5_fu_2613_p3 = ((tmp_112_5_fu_2609_p2[0:0] === 1'b1) ? maxnum_2_4_reg_3759 : num_1_4_reg_3766);

assign maxnum_3_6_fu_2663_p3 = ((tmp_112_6_fu_2657_p2[0:0] === 1'b1) ? maxnum_2_5_fu_2629_p3 : num_1_5_fu_2643_p3);

assign maxnum_3_7_fu_2720_p3 = ((tmp_112_7_fu_2714_p2[0:0] === 1'b1) ? maxnum_2_6_fu_2681_p3 : num_1_6_fu_2696_p3);

assign maxnum_3_8_fu_2774_p3 = ((tmp_112_8_fu_2769_p2[0:0] === 1'b1) ? maxnum_2_7_cast1_cas_fu_2761_p1 : num_1_7_reg_3778);

assign maxnum_3_9_fu_2826_p3 = ((tmp_112_9_fu_2820_p2[0:0] === 1'b1) ? maxnum_2_8_fu_2791_p3 : num_1_8_fu_2806_p3);

assign maxnum_3_s_fu_2879_p3 = ((tmp_112_s_fu_2873_p2[0:0] === 1'b1) ? maxnum_2_9_fu_2844_p3 : num_1_9_fu_2859_p3);

assign maxnum_fu_3187_p3 = ((tmp_55_fu_3181_p2[0:0] === 1'b1) ? maxnum_2_14_cast1_ca_fu_3162_p1 : num_1_14_fu_3173_p3);

assign neg1_fu_1602_p2 = (17'd0 - tmp_31_fu_1596_p2);

assign neg2_fu_1634_p2 = (17'd0 - tmp_33_fu_1628_p2);

assign neg3_fu_1670_p2 = (17'd0 - tmp_35_fu_1664_p2);

assign neg4_fu_1706_p2 = (17'd0 - tmp_37_fu_1700_p2);

assign neg5_10_fu_2153_p2 = (17'd0 - tmp_110_10_fu_2147_p2);

assign neg5_11_fu_2185_p2 = (17'd0 - tmp_110_11_fu_2179_p2);

assign neg5_12_fu_2224_p2 = (17'd0 - tmp_110_12_fu_2218_p2);

assign neg5_13_fu_2263_p2 = (17'd0 - tmp_110_13_fu_2257_p2);

assign neg5_14_fu_2302_p2 = (17'd0 - tmp_110_14_fu_2296_p2);

assign neg5_1_fu_1777_p2 = (17'd0 - tmp_110_1_fu_1771_p2);

assign neg5_2_fu_1816_p2 = (17'd0 - tmp_110_2_fu_1810_p2);

assign neg5_3_fu_1855_p2 = (17'd0 - tmp_110_3_fu_1849_p2);

assign neg5_4_fu_1887_p2 = (17'd0 - tmp_110_4_fu_1881_p2);

assign neg5_5_fu_1926_p2 = (17'd0 - tmp_110_5_fu_1920_p2);

assign neg5_6_fu_1965_p2 = (17'd0 - tmp_110_6_fu_1959_p2);

assign neg5_7_fu_2004_p2 = (17'd0 - tmp_110_7_fu_1998_p2);

assign neg5_8_fu_2036_p2 = (17'd0 - tmp_110_8_fu_2030_p2);

assign neg5_9_fu_2075_p2 = (17'd0 - tmp_110_9_fu_2069_p2);

assign neg5_fu_1738_p2 = (17'd0 - tmp_43_fu_1732_p2);

assign neg5_s_fu_2114_p2 = (17'd0 - tmp_110_s_fu_2108_p2);

assign neg_fu_1557_p2 = (17'd0 - tmp_17_fu_1551_p2);

assign not_sel_tmp_fu_3209_p2 = (sel_tmp43_fu_3205_p2 ^ 1'd1);

assign not_tmp_111_1_fu_2416_p2 = (tmp_111_1_reg_3650 ^ 1'd1);

assign not_tmp_s_fu_2328_p2 = (tmp_32_reg_3623 ^ 1'd1);

assign num_1_10_fu_2959_p3 = ((sel_tmp28_fu_2940_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp29_fu_2952_p3);

assign num_1_11_fu_3012_p3 = ((sel_tmp31_fu_2992_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp32_fu_3005_p3);

assign num_1_12_fu_3065_p3 = ((sel_tmp34_fu_3045_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp35_fu_3058_p3);

assign num_1_13_cast_fu_3120_p1 = num_1_13_fu_3112_p3;

assign num_1_13_fu_3112_p3 = ((sel_tmp37_fu_3093_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp38_fu_3105_p3);

assign num_1_14_fu_3173_p3 = ((sel_tmp40_fu_3149_p2[0:0] === 1'b1) ? 5'd0 : sel_tmp41_fu_3166_p3);

assign num_1_1_fu_2430_p3 = ((tmp_111_1_reg_3650[0:0] === 1'b1) ? num_2_1_fu_2409_p3 : 2'd0);

assign num_1_2_cast_fu_2490_p1 = num_1_2_fu_2482_p3;

assign num_1_2_fu_2482_p3 = ((sel_tmp6_fu_2462_p2[0:0] === 1'b1) ? 2'd0 : sel_tmp8_fu_2475_p3);

assign num_1_3_fu_2543_p3 = ((sel_tmp1_fu_2519_p2[0:0] === 1'b1) ? 3'd0 : sel_tmp2_fu_2536_p3);

assign num_1_4_fu_2596_p3 = ((sel_tmp4_fu_2576_p2[0:0] === 1'b1) ? 3'd0 : sel_tmp7_fu_2589_p3);

assign num_1_5_fu_2643_p3 = ((sel_tmp10_fu_2624_p2[0:0] === 1'b1) ? 3'd0 : sel_tmp11_fu_2636_p3);

assign num_1_6_cast_fu_2704_p1 = num_1_6_fu_2696_p3;

assign num_1_6_fu_2696_p3 = ((sel_tmp13_fu_2676_p2[0:0] === 1'b1) ? 3'd0 : sel_tmp14_fu_2689_p3);

assign num_1_7_fu_2753_p3 = ((sel_tmp16_fu_2733_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp17_fu_2746_p3);

assign num_1_8_fu_2806_p3 = ((sel_tmp19_fu_2786_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp20_fu_2799_p3);

assign num_1_9_fu_2859_p3 = ((sel_tmp22_fu_2839_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp23_fu_2852_p3);

assign num_1_s_fu_2912_p3 = ((sel_tmp25_fu_2892_p2[0:0] === 1'b1) ? 4'd0 : sel_tmp26_fu_2905_p3);

assign num_2_10_fu_2920_p2 = (num_1_s_reg_3792 + 4'd1);

assign num_2_11_fu_2967_p2 = (num_1_10_fu_2959_p3 + 4'd1);

assign num_2_12_fu_3020_p2 = (num_1_11_fu_3012_p3 + 4'd1);

assign num_2_13_fu_3073_p2 = (num_1_12_reg_3806 + 4'd1);

assign num_2_14_fu_3124_p2 = (num_1_13_cast_fu_3120_p1 + 5'd1);

assign num_2_1_fu_2409_p3 = ((tmp_44_reg_3644[0:0] === 1'b1) ? 2'd2 : 2'd1);

assign num_2_2_fu_2437_p2 = (num_1_1_fu_2430_p3 + 2'd1);

assign num_2_3_fu_2494_p2 = (num_1_2_cast_fu_2490_p1 + 3'd1);

assign num_2_4_fu_2551_p2 = (num_1_3_fu_2543_p3 + 3'd1);

assign num_2_5_fu_2604_p2 = (num_1_4_reg_3766 + 3'd1);

assign num_2_6_fu_2651_p2 = (num_1_5_fu_2643_p3 + 3'd1);

assign num_2_7_fu_2708_p2 = (num_1_6_cast_fu_2704_p1 + 4'd1);

assign num_2_8_fu_2764_p2 = (num_1_7_reg_3778 + 4'd1);

assign num_2_9_fu_2814_p2 = (num_1_8_fu_2806_p3 + 4'd1);

assign num_2_s_fu_2867_p2 = (num_1_9_fu_2859_p3 + 4'd1);

assign p1_fu_1534_p1 = $signed(tmp_5_reg_3532);

assign p2_fu_1537_p1 = $signed(tmp_10_reg_3537);

assign p3_fu_1540_p1 = $signed(tmp_16_reg_3542);

assign p4_fu_1586_p1 = $signed(tmp_24_reg_3547);

assign p5_fu_1589_p1 = $signed(tmp_30_reg_3552);

assign p_0_fu_3215_p2 = (sel_tmp42_fu_3201_p2 & not_sel_tmp_fu_3209_p2);

assign p_cast_fu_2333_p1 = not_tmp_s_fu_2328_p2;

assign p_shl12_10_cast_fu_1418_p1 = p_shl12_10_fu_1410_p3;

assign p_shl12_10_fu_1410_p3 = {{tmp_88_fu_1400_p4}, {7'd0}};

assign p_shl12_11_cast_fu_1496_p1 = p_shl12_11_fu_1488_p3;

assign p_shl12_11_fu_1488_p3 = {{tmp_92_fu_1478_p4}, {7'd0}};

assign p_shl12_1_cast_fu_638_p1 = p_shl12_1_fu_630_p3;

assign p_shl12_1_fu_630_p3 = {{tmp_46_fu_620_p4}, {7'd0}};

assign p_shl12_2_cast_fu_716_p1 = p_shl12_2_fu_708_p3;

assign p_shl12_2_fu_708_p3 = {{tmp_50_fu_698_p4}, {7'd0}};

assign p_shl12_3_cast_fu_794_p1 = p_shl12_3_fu_786_p3;

assign p_shl12_3_fu_786_p3 = {{tmp_54_fu_776_p4}, {7'd0}};

assign p_shl12_4_cast_fu_1262_p1 = p_shl12_4_fu_1254_p3;

assign p_shl12_4_fu_1254_p3 = {{tmp_80_fu_1244_p4}, {7'd0}};

assign p_shl12_5_cast_fu_872_p1 = p_shl12_5_fu_864_p3;

assign p_shl12_5_fu_864_p3 = {{tmp_60_fu_854_p4}, {7'd0}};

assign p_shl12_6_cast_fu_950_p1 = p_shl12_6_fu_942_p3;

assign p_shl12_6_fu_942_p3 = {{tmp_64_fu_932_p4}, {7'd0}};

assign p_shl12_7_cast_fu_1028_p1 = p_shl12_7_fu_1020_p3;

assign p_shl12_7_fu_1020_p3 = {{tmp_68_fu_1010_p4}, {7'd0}};

assign p_shl12_8_cast_fu_1340_p1 = p_shl12_8_fu_1332_p3;

assign p_shl12_8_fu_1332_p3 = {{tmp_84_fu_1322_p4}, {7'd0}};

assign p_shl12_9_cast_fu_1106_p1 = p_shl12_9_fu_1098_p3;

assign p_shl12_9_fu_1098_p3 = {{tmp_72_fu_1088_p4}, {7'd0}};

assign p_shl12_cast_fu_1184_p1 = p_shl12_s_fu_1176_p3;

assign p_shl12_s_fu_1176_p3 = {{tmp_76_fu_1166_p4}, {7'd0}};

assign p_shl13_10_cast_fu_1430_p1 = p_shl13_10_fu_1422_p3;

assign p_shl13_10_fu_1422_p3 = {{tmp_88_fu_1400_p4}, {3'd0}};

assign p_shl13_11_cast_fu_1508_p1 = p_shl13_11_fu_1500_p3;

assign p_shl13_11_fu_1500_p3 = {{tmp_92_fu_1478_p4}, {3'd0}};

assign p_shl13_1_cast_fu_650_p1 = p_shl13_1_fu_642_p3;

assign p_shl13_1_fu_642_p3 = {{tmp_46_fu_620_p4}, {3'd0}};

assign p_shl13_2_cast_fu_728_p1 = p_shl13_2_fu_720_p3;

assign p_shl13_2_fu_720_p3 = {{tmp_50_fu_698_p4}, {3'd0}};

assign p_shl13_3_cast_fu_806_p1 = p_shl13_3_fu_798_p3;

assign p_shl13_3_fu_798_p3 = {{tmp_54_fu_776_p4}, {3'd0}};

assign p_shl13_4_cast_fu_1274_p1 = p_shl13_4_fu_1266_p3;

assign p_shl13_4_fu_1266_p3 = {{tmp_80_fu_1244_p4}, {3'd0}};

assign p_shl13_5_cast_fu_884_p1 = p_shl13_5_fu_876_p3;

assign p_shl13_5_fu_876_p3 = {{tmp_60_fu_854_p4}, {3'd0}};

assign p_shl13_6_cast_fu_962_p1 = p_shl13_6_fu_954_p3;

assign p_shl13_6_fu_954_p3 = {{tmp_64_fu_932_p4}, {3'd0}};

assign p_shl13_7_cast_fu_1040_p1 = p_shl13_7_fu_1032_p3;

assign p_shl13_7_fu_1032_p3 = {{tmp_68_fu_1010_p4}, {3'd0}};

assign p_shl13_8_cast_fu_1352_p1 = p_shl13_8_fu_1344_p3;

assign p_shl13_8_fu_1344_p3 = {{tmp_84_fu_1322_p4}, {3'd0}};

assign p_shl13_9_cast_fu_1118_p1 = p_shl13_9_fu_1110_p3;

assign p_shl13_9_fu_1110_p3 = {{tmp_72_fu_1088_p4}, {3'd0}};

assign p_shl13_cast_fu_1196_p1 = p_shl13_s_fu_1188_p3;

assign p_shl13_s_fu_1188_p3 = {{tmp_76_fu_1166_p4}, {3'd0}};

assign p_shl1_cast_fu_482_p1 = p_shl1_fu_474_p3;

assign p_shl1_fu_474_p3 = {{tmp_21_fu_464_p4}, {7'd0}};

assign p_shl2_cast_fu_494_p1 = p_shl2_fu_486_p3;

assign p_shl2_fu_486_p3 = {{tmp_21_fu_464_p4}, {3'd0}};

assign p_shl3_cast_fu_416_p1 = p_shl3_fu_408_p3;

assign p_shl3_fu_408_p3 = {{tmp_13_fu_386_p4}, {3'd0}};

assign p_shl4_cast_fu_326_p1 = p_shl4_fu_318_p3;

assign p_shl4_fu_318_p3 = {{tmp_3_fu_308_p4}, {7'd0}};

assign p_shl5_cast_fu_338_p1 = p_shl5_fu_330_p3;

assign p_shl5_fu_330_p3 = {{tmp_3_fu_308_p4}, {3'd0}};

assign p_shl6_cast_fu_248_p1 = p_shl6_fu_240_p3;

assign p_shl6_fu_240_p3 = {{tmp_fu_230_p4}, {7'd0}};

assign p_shl7_cast_fu_260_p1 = p_shl7_fu_252_p3;

assign p_shl7_fu_252_p3 = {{tmp_fu_230_p4}, {3'd0}};

assign p_shl8_cast_fu_560_p1 = p_shl8_fu_552_p3;

assign p_shl8_fu_552_p3 = {{tmp_27_fu_542_p4}, {7'd0}};

assign p_shl9_cast_fu_572_p1 = p_shl9_fu_564_p3;

assign p_shl9_fu_564_p3 = {{tmp_27_fu_542_p4}, {3'd0}};

assign p_shl_cast_fu_404_p1 = p_shl_fu_396_p3;

assign p_shl_fu_396_p3 = {{tmp_13_fu_386_p4}, {7'd0}};

assign sel_tmp10_fu_2624_p2 = (tmp_111_4_reg_3671_pp0_iter2_reg & sel_tmp9_fu_2619_p2);

assign sel_tmp11_fu_2636_p3 = ((tmp_111_5_reg_3678_pp0_iter2_reg[0:0] === 1'b1) ? num_2_5_fu_2604_p2 : 3'd0);

assign sel_tmp12_fu_2671_p2 = (tmp_111_6_reg_3685_pp0_iter2_reg ^ 1'd1);

assign sel_tmp13_fu_2676_p2 = (tmp_111_5_reg_3678_pp0_iter2_reg & sel_tmp12_fu_2671_p2);

assign sel_tmp14_fu_2689_p3 = ((tmp_111_6_reg_3685_pp0_iter2_reg[0:0] === 1'b1) ? num_2_6_fu_2651_p2 : 3'd0);

assign sel_tmp15_fu_2728_p2 = (tmp_111_7_reg_3692_pp0_iter2_reg ^ 1'd1);

assign sel_tmp16_fu_2733_p2 = (tmp_111_6_reg_3685_pp0_iter2_reg & sel_tmp15_fu_2728_p2);

assign sel_tmp17_fu_2746_p3 = ((tmp_111_7_reg_3692_pp0_iter2_reg[0:0] === 1'b1) ? num_2_7_fu_2708_p2 : 4'd0);

assign sel_tmp18_fu_2781_p2 = (tmp_111_8_reg_3699_pp0_iter3_reg ^ 1'd1);

assign sel_tmp19_fu_2786_p2 = (tmp_111_7_reg_3692_pp0_iter3_reg & sel_tmp18_fu_2781_p2);

assign sel_tmp1_fu_2519_p2 = (tmp_111_2_reg_3657 & sel_tmp_fu_2514_p2);

assign sel_tmp20_fu_2799_p3 = ((tmp_111_8_reg_3699_pp0_iter3_reg[0:0] === 1'b1) ? num_2_8_fu_2764_p2 : 4'd0);

assign sel_tmp21_fu_2834_p2 = (tmp_111_9_reg_3706_pp0_iter3_reg ^ 1'd1);

assign sel_tmp22_fu_2839_p2 = (tmp_111_8_reg_3699_pp0_iter3_reg & sel_tmp21_fu_2834_p2);

assign sel_tmp23_fu_2852_p3 = ((tmp_111_9_reg_3706_pp0_iter3_reg[0:0] === 1'b1) ? num_2_9_fu_2814_p2 : 4'd0);

assign sel_tmp24_fu_2887_p2 = (tmp_111_s_reg_3713_pp0_iter3_reg ^ 1'd1);

assign sel_tmp25_fu_2892_p2 = (tmp_111_9_reg_3706_pp0_iter3_reg & sel_tmp24_fu_2887_p2);

assign sel_tmp26_fu_2905_p3 = ((tmp_111_s_reg_3713_pp0_iter3_reg[0:0] === 1'b1) ? num_2_s_fu_2867_p2 : 4'd0);

assign sel_tmp27_fu_2935_p2 = (tmp_111_10_reg_3720_pp0_iter4_reg ^ 1'd1);

assign sel_tmp28_fu_2940_p2 = (tmp_111_s_reg_3713_pp0_iter4_reg & sel_tmp27_fu_2935_p2);

assign sel_tmp29_fu_2952_p3 = ((tmp_111_10_reg_3720_pp0_iter4_reg[0:0] === 1'b1) ? num_2_10_fu_2920_p2 : 4'd0);

assign sel_tmp2_fu_2536_p3 = ((tmp_111_3_reg_3664[0:0] === 1'b1) ? num_2_3_fu_2494_p2 : 3'd0);

assign sel_tmp30_fu_2987_p2 = (tmp_111_11_reg_3727_pp0_iter4_reg ^ 1'd1);

assign sel_tmp31_fu_2992_p2 = (tmp_111_10_reg_3720_pp0_iter4_reg & sel_tmp30_fu_2987_p2);

assign sel_tmp32_fu_3005_p3 = ((tmp_111_11_reg_3727_pp0_iter4_reg[0:0] === 1'b1) ? num_2_11_fu_2967_p2 : 4'd0);

assign sel_tmp33_fu_3040_p2 = (tmp_111_12_reg_3734_pp0_iter4_reg ^ 1'd1);

assign sel_tmp34_fu_3045_p2 = (tmp_111_11_reg_3727_pp0_iter4_reg & sel_tmp33_fu_3040_p2);

assign sel_tmp35_fu_3058_p3 = ((tmp_111_12_reg_3734_pp0_iter4_reg[0:0] === 1'b1) ? num_2_12_fu_3020_p2 : 4'd0);

assign sel_tmp36_fu_3088_p2 = (tmp_111_13_reg_3741_pp0_iter5_reg ^ 1'd1);

assign sel_tmp37_fu_3093_p2 = (tmp_111_12_reg_3734_pp0_iter5_reg & sel_tmp36_fu_3088_p2);

assign sel_tmp38_fu_3105_p3 = ((tmp_111_13_reg_3741_pp0_iter5_reg[0:0] === 1'b1) ? num_2_13_fu_3073_p2 : 4'd0);

assign sel_tmp39_fu_3144_p2 = (tmp_111_14_reg_3748_pp0_iter5_reg ^ 1'd1);

assign sel_tmp3_fu_2571_p2 = (tmp_111_4_reg_3671 ^ 1'd1);

assign sel_tmp40_fu_3149_p2 = (tmp_111_13_reg_3741_pp0_iter5_reg & sel_tmp39_fu_3144_p2);

assign sel_tmp41_fu_3166_p3 = ((tmp_111_14_reg_3748_pp0_iter5_reg[0:0] === 1'b1) ? num_2_14_fu_3124_p2 : 5'd0);

assign sel_tmp42_fu_3201_p2 = (tmp_59_reg_3813 & tmp_18_reg_3617_pp0_iter6_reg);

assign sel_tmp43_fu_3205_p2 = (tmp_18_reg_3617_pp0_iter6_reg & icmp_reg_3754_pp0_iter6_reg);

assign sel_tmp4_fu_2576_p2 = (tmp_111_3_reg_3664 & sel_tmp3_fu_2571_p2);

assign sel_tmp5_fu_2457_p2 = (tmp_111_2_reg_3657 ^ 1'd1);

assign sel_tmp6_fu_2462_p2 = (tmp_111_1_reg_3650 & sel_tmp5_fu_2457_p2);

assign sel_tmp7_fu_2589_p3 = ((tmp_111_4_reg_3671[0:0] === 1'b1) ? num_2_4_fu_2551_p2 : 3'd0);

assign sel_tmp8_fu_2475_p3 = ((tmp_111_2_reg_3657[0:0] === 1'b1) ? num_2_2_fu_2437_p2 : 2'd0);

assign sel_tmp9_fu_2619_p2 = (tmp_111_5_reg_3678_pp0_iter2_reg ^ 1'd1);

assign sel_tmp_fu_2514_p2 = (tmp_111_3_reg_3664 ^ 1'd1);

assign threshold_data_cast1_fu_1577_p1 = $signed(threshold_data_read_reg_3527);

assign tmp_105_10_fu_1434_p2 = (p_shl12_10_cast_fu_1418_p1 - p_shl13_10_cast_fu_1430_p1);

assign tmp_105_11_fu_1512_p2 = (p_shl12_11_cast_fu_1496_p1 - p_shl13_11_cast_fu_1508_p1);

assign tmp_105_1_fu_654_p2 = (p_shl12_1_cast_fu_638_p1 - p_shl13_1_cast_fu_650_p1);

assign tmp_105_2_fu_732_p2 = (p_shl12_2_cast_fu_716_p1 - p_shl13_2_cast_fu_728_p1);

assign tmp_105_3_fu_810_p2 = (p_shl12_3_cast_fu_794_p1 - p_shl13_3_cast_fu_806_p1);

assign tmp_105_4_fu_1278_p2 = (p_shl12_4_cast_fu_1262_p1 - p_shl13_4_cast_fu_1274_p1);

assign tmp_105_5_fu_888_p2 = (p_shl12_5_cast_fu_872_p1 - p_shl13_5_cast_fu_884_p1);

assign tmp_105_6_fu_966_p2 = (p_shl12_6_cast_fu_950_p1 - p_shl13_6_cast_fu_962_p1);

assign tmp_105_7_fu_1044_p2 = (p_shl12_7_cast_fu_1028_p1 - p_shl13_7_cast_fu_1040_p1);

assign tmp_105_8_fu_1356_p2 = (p_shl12_8_cast_fu_1340_p1 - p_shl13_8_cast_fu_1352_p1);

assign tmp_105_9_fu_1122_p2 = (p_shl12_9_cast_fu_1106_p1 - p_shl13_9_cast_fu_1118_p1);

assign tmp_105_s_fu_1200_p2 = (p_shl12_cast_fu_1184_p1 - p_shl13_cast_fu_1196_p1);

assign tmp_109_10_cast_fu_2253_p1 = $unsigned(tmp_90_fu_2250_p1);

assign tmp_109_11_cast_fu_2292_p1 = $unsigned(tmp_94_fu_2289_p1);

assign tmp_109_1_cast_fu_1767_p1 = $unsigned(tmp_48_fu_1764_p1);

assign tmp_109_2_cast_fu_1806_p1 = $unsigned(tmp_52_fu_1803_p1);

assign tmp_109_3_cast_fu_1845_p1 = $unsigned(tmp_57_fu_1842_p1);

assign tmp_109_4_cast_fu_2143_p1 = $unsigned(tmp_82_fu_2140_p1);

assign tmp_109_5_cast_fu_1916_p1 = $unsigned(tmp_62_fu_1913_p1);

assign tmp_109_6_cast_fu_1955_p1 = $unsigned(tmp_66_fu_1952_p1);

assign tmp_109_7_cast_fu_1994_p1 = $unsigned(tmp_70_fu_1991_p1);

assign tmp_109_8_cast_fu_2214_p1 = $unsigned(tmp_86_fu_2211_p1);

assign tmp_109_9_cast_fu_2065_p1 = $unsigned(tmp_74_fu_2062_p1);

assign tmp_109_cast_fu_2104_p1 = $unsigned(tmp_78_fu_2101_p1);

assign tmp_110_10_fu_2147_p2 = (tmp_109_4_cast_fu_2143_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_11_fu_2179_p2 = (tmp_66_cast_fu_1696_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_12_fu_2218_p2 = (tmp_109_8_cast_fu_2214_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_13_fu_2257_p2 = (tmp_109_10_cast_fu_2253_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_14_fu_2296_p2 = (tmp_109_11_cast_fu_2292_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_1_fu_1771_p2 = (tmp_109_1_cast_fu_1767_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_2_fu_1810_p2 = (tmp_109_2_cast_fu_1806_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_3_fu_1849_p2 = (tmp_109_3_cast_fu_1845_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_4_fu_1881_p2 = (tmp_63_cast_fu_1660_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_5_fu_1920_p2 = (tmp_109_5_cast_fu_1916_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_6_fu_1959_p2 = (tmp_109_6_cast_fu_1955_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_7_fu_1998_p2 = (tmp_109_7_cast_fu_1994_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_8_fu_2030_p2 = (tmp_32_cast_fu_1543_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_9_fu_2069_p2 = (tmp_109_9_cast_fu_2065_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_110_s_fu_2108_p2 = (tmp_109_cast_fu_2104_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_111_10_fu_2173_p2 = (($signed(abs5_10_fu_2165_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_11_fu_2205_p2 = (($signed(abs5_11_fu_2197_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_12_fu_2244_p2 = (($signed(abs5_12_fu_2236_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_13_fu_2283_p2 = (($signed(abs5_13_fu_2275_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_14_fu_2322_p2 = (($signed(abs5_14_fu_2314_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_1_fu_1797_p2 = (($signed(abs5_1_fu_1789_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_2_fu_1836_p2 = (($signed(abs5_2_fu_1828_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_3_fu_1875_p2 = (($signed(abs5_3_fu_1867_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_4_fu_1907_p2 = (($signed(abs5_4_fu_1899_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_5_fu_1946_p2 = (($signed(abs5_5_fu_1938_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_6_fu_1985_p2 = (($signed(abs5_6_fu_1977_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_7_fu_2024_p2 = (($signed(abs5_7_fu_2016_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_8_fu_2056_p2 = (($signed(abs5_8_fu_2048_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_9_fu_2095_p2 = (($signed(abs5_9_fu_2087_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_111_s_fu_2134_p2 = (($signed(abs5_s_fu_2126_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_112_10_fu_2973_p2 = ((maxnum_2_10_fu_2945_p3 > num_1_10_fu_2959_p3) ? 1'b1 : 1'b0);

assign tmp_112_11_fu_3026_p2 = ((maxnum_2_11_fu_2997_p3 > num_1_11_fu_3012_p3) ? 1'b1 : 1'b0);

assign tmp_112_12_fu_3078_p2 = ((maxnum_2_12_reg_3799 > num_1_12_reg_3806) ? 1'b1 : 1'b0);

assign tmp_112_13_fu_3130_p2 = ((maxnum_2_13_fu_3098_p3 > num_1_13_fu_3112_p3) ? 1'b1 : 1'b0);

assign tmp_112_1_fu_2925_p2 = ((maxnum_2_s_reg_3785 > num_1_s_reg_3792) ? 1'b1 : 1'b0);

assign tmp_112_2_fu_2443_p2 = ((maxnum_2_1_cast_fu_2426_p1 > num_1_1_fu_2430_p3) ? 1'b1 : 1'b0);

assign tmp_112_3_fu_2500_p2 = ((maxnum_2_2_fu_2467_p3 > num_1_2_fu_2482_p3) ? 1'b1 : 1'b0);

assign tmp_112_4_fu_2557_p2 = ((maxnum_2_3_cast1_cas_fu_2532_p1 > num_1_3_fu_2543_p3) ? 1'b1 : 1'b0);

assign tmp_112_5_fu_2609_p2 = ((maxnum_2_4_reg_3759 > num_1_4_reg_3766) ? 1'b1 : 1'b0);

assign tmp_112_6_fu_2657_p2 = ((maxnum_2_5_fu_2629_p3 > num_1_5_fu_2643_p3) ? 1'b1 : 1'b0);

assign tmp_112_7_fu_2714_p2 = ((maxnum_2_6_fu_2681_p3 > num_1_6_fu_2696_p3) ? 1'b1 : 1'b0);

assign tmp_112_8_fu_2769_p2 = ((maxnum_2_7_cast1_cas_fu_2761_p1 > num_1_7_reg_3778) ? 1'b1 : 1'b0);

assign tmp_112_9_fu_2820_p2 = ((maxnum_2_8_fu_2791_p3 > num_1_8_fu_2806_p3) ? 1'b1 : 1'b0);

assign tmp_112_s_fu_2873_p2 = ((maxnum_2_9_fu_2844_p3 > num_1_9_fu_2859_p3) ? 1'b1 : 1'b0);

assign tmp_13_fu_386_p4 = {{window_val_0_3_rea_int_reg[23:16]}};

assign tmp_14_fu_420_p2 = (p_shl_cast_fu_404_p1 - p_shl3_cast_fu_416_p1);

assign tmp_17_fu_1551_p2 = (tmp_32_cast_fu_1543_p1 - tmp_33_cast_fu_1547_p1);

assign tmp_18_fu_1580_p2 = (($signed(abs_fu_1569_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_1_fu_342_p2 = (p_shl4_cast_fu_326_p1 - p_shl5_cast_fu_338_p1);

assign tmp_21_fu_464_p4 = {{window_val_3_6_rea_int_reg[23:16]}};

assign tmp_22_fu_498_p2 = (p_shl1_cast_fu_482_p1 - p_shl2_cast_fu_494_p1);

assign tmp_27_fu_542_p4 = {{window_val_3_0_rea_int_reg[23:16]}};

assign tmp_28_fu_576_p2 = (p_shl8_cast_fu_560_p1 - p_shl9_cast_fu_572_p1);

assign tmp_31_fu_1596_p2 = (tmp_58_cast_fu_1592_p1 - tmp_32_cast_fu_1543_p1);

assign tmp_32_cast_fu_1543_p1 = $unsigned(p2_fu_1537_p1);

assign tmp_32_fu_1622_p2 = (($signed(abs1_fu_1614_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_33_cast_fu_1547_p1 = $unsigned(p3_fu_1540_p1);

assign tmp_33_fu_1628_p2 = (tmp_58_cast_fu_1592_p1 - tmp_33_cast_fu_1547_p1);

assign tmp_34_fu_1654_p2 = (($signed(abs2_fu_1646_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_35_fu_1664_p2 = (tmp_58_cast_fu_1592_p1 - tmp_63_cast_fu_1660_p1);

assign tmp_36_fu_1690_p2 = (($signed(abs3_fu_1682_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_37_fu_1700_p2 = (tmp_58_cast_fu_1592_p1 - tmp_66_cast_fu_1696_p1);

assign tmp_38_fu_1726_p2 = (($signed(abs4_fu_1718_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_39_fu_2374_p3 = k_1_s_fu_2357_p3[32'd1];

assign tmp_3_fu_308_p4 = {{window_val_6_3_rea_int_reg[23:16]}};

assign tmp_40_fu_2382_p1 = tmp_39_fu_2374_p3;

assign tmp_41_fu_2386_p4 = {{k_3_fu_2368_p2[2:1]}};

assign tmp_42_fu_2396_p3 = ((tmp_38_reg_3639[0:0] === 1'b1) ? tmp_40_fu_2382_p1 : tmp_41_fu_2386_p4);

assign tmp_43_fu_1732_p2 = (tmp_33_cast_fu_1547_p1 - tmp_58_cast_fu_1592_p1);

assign tmp_44_fu_1758_p2 = (($signed(abs5_fu_1750_p3) > $signed(threshold_data_cast1_fu_1577_p1)) ? 1'b1 : 1'b0);

assign tmp_45_fu_598_p1 = window_val_0_4_rea_int_reg[7:0];

assign tmp_46_fu_620_p4 = {{window_val_0_4_rea_int_reg[23:16]}};

assign tmp_48_fu_1764_p1 = $signed(tmp_47_reg_3557);

assign tmp_49_fu_676_p1 = window_val_1_5_rea_int_reg[7:0];

assign tmp_50_fu_698_p4 = {{window_val_1_5_rea_int_reg[23:16]}};

assign tmp_52_fu_1803_p1 = $signed(tmp_51_reg_3562);

assign tmp_53_fu_754_p1 = window_val_2_6_rea_int_reg[7:0];

assign tmp_54_fu_776_p4 = {{window_val_2_6_rea_int_reg[23:16]}};

assign tmp_55_fu_3181_p2 = ((maxnum_2_14_cast1_ca_fu_3162_p1 > num_1_14_fu_3173_p3) ? 1'b1 : 1'b0);

assign tmp_57_fu_1842_p1 = $signed(tmp_56_reg_3567);

assign tmp_58_cast_fu_1592_p1 = $unsigned(p1_fu_1534_p1);

assign tmp_58_fu_832_p1 = window_val_4_6_rea_int_reg[7:0];

assign tmp_59_fu_3195_p2 = ((maxnum_fu_3187_p3 > 5'd8) ? 1'b1 : 1'b0);

assign tmp_60_fu_854_p4 = {{window_val_4_6_rea_int_reg[23:16]}};

assign tmp_62_fu_1913_p1 = $signed(tmp_61_reg_3572);

assign tmp_63_cast_fu_1660_p1 = $unsigned(p4_fu_1586_p1);

assign tmp_63_fu_910_p1 = window_val_5_5_rea_int_reg[7:0];

assign tmp_64_fu_932_p4 = {{window_val_5_5_rea_int_reg[23:16]}};

assign tmp_66_cast_fu_1696_p1 = $unsigned(p5_fu_1589_p1);

assign tmp_66_fu_1952_p1 = $signed(tmp_65_reg_3577);

assign tmp_67_fu_988_p1 = window_val_6_4_rea_int_reg[7:0];

assign tmp_68_fu_1010_p4 = {{window_val_6_4_rea_int_reg[23:16]}};

assign tmp_6_fu_264_p2 = (p_shl6_cast_fu_248_p1 - p_shl7_cast_fu_260_p1);

assign tmp_70_fu_1991_p1 = $signed(tmp_69_reg_3582);

assign tmp_71_fu_1066_p1 = window_val_6_2_rea_int_reg[7:0];

assign tmp_72_fu_1088_p4 = {{window_val_6_2_rea_int_reg[23:16]}};

assign tmp_74_fu_2062_p1 = $signed(tmp_73_reg_3587);

assign tmp_75_fu_1144_p1 = window_val_5_1_rea_int_reg[7:0];

assign tmp_76_fu_1166_p4 = {{window_val_5_1_rea_int_reg[23:16]}};

assign tmp_78_fu_2101_p1 = $signed(tmp_77_reg_3592);

assign tmp_79_fu_1222_p1 = window_val_4_0_rea_int_reg[7:0];

assign tmp_80_fu_1244_p4 = {{window_val_4_0_rea_int_reg[23:16]}};

assign tmp_82_fu_2140_p1 = $signed(tmp_81_reg_3597);

assign tmp_83_fu_1300_p1 = window_val_2_0_rea_int_reg[7:0];

assign tmp_84_fu_1322_p4 = {{window_val_2_0_rea_int_reg[23:16]}};

assign tmp_86_fu_2211_p1 = $signed(tmp_85_reg_3602);

assign tmp_87_fu_1378_p1 = window_val_1_1_rea_int_reg[7:0];

assign tmp_88_fu_1400_p4 = {{window_val_1_1_rea_int_reg[23:16]}};

assign tmp_90_fu_2250_p1 = $signed(tmp_89_reg_3607);

assign tmp_91_fu_1456_p1 = window_val_0_2_rea_int_reg[7:0];

assign tmp_92_fu_1478_p4 = {{window_val_0_2_rea_int_reg[23:16]}};

assign tmp_94_fu_2289_p1 = $signed(tmp_93_reg_3612);

assign tmp_fu_230_p4 = {{window_val_3_3_rea_int_reg[23:16]}};

endmodule //computerWindow
